<?php

namespace Numa\DOAAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListingFieldTreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingfieldRepository extends EntityRepository {

    public function findAllByCaption($caption, $categories = array()) {

        $qb = $this->getEntityManager()
                ->createQueryBuilder();
        $qb->select('lf')
                ->from('NumaDOAAdminBundle:Listingfield', 'lf')
                ->andWhere('l.caption like :caption')
                ->andWhere('l.category_sid like :categories')                                
                ->setParameter('property', "%" . $property . "%");
        if(is_array($categories) && !empty($categories)){
                $qb    ->andWhere('r.winner IN (:categories)')
                ->setParameter('categories', $categories);
        ;
        }
        $res = $query->getResult(); //getOneOrNullResult();
        return $res;
    }

}
