<?php

namespace Numa\DOAAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListingFieldTreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingFieldTreeRepository extends EntityRepository {

    public function getJsonTree($root = 1, $deep = 2) {
        $qb = $this->getEntityManager()
                ->createQueryBuilder();
        $query = $qb->select('tp')
                ->from('NumaDOAAdminBundle:ListingfieldTree', 'tp')
                ->where('tp.id=:field_id')
                ->setParameter('field_id', 291)

                ->getQuery();
        ;

        $res = $query->getOneOrNullResult();
        ;
        //\Doctrine\Common\Util\Debug::dump(count($res->getChildren()));
        ;
        
        return $res;
    }

}
