<?php

namespace Numa\DOAAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListingFieldTreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingFieldTreeRepository extends EntityRepository {

    public function getJsonTreeModels($fieldId,$root = 1, $deep = 2) {
        $qb = $this->getEntityManager()
                ->createQueryBuilder();
        $query = $qb->select('tp')
                ->from('NumaDOAAdminBundle:ListingFieldTree', 'tp')
                ->where('tp.listing_field_id=:field_id')
                ->setParameter('field_id', $fieldId)
                ->getQuery();
        ;

        $results = $query->getResult();
        $jsonArray = array();
        foreach($results as $res){
            foreach($res->getChildren() as $children){
                $name = str_replace(array("'",".",",","}","{","\""),"",$children->getName());
                $jsonArray[$res->getId()][] = array($children->getId()=>  $name);
            }
        }

        
        return json_encode($jsonArray);
    }
    
        public function findAllBy($fieldId) {
        $qb = $this->getEntityManager()
                ->createQueryBuilder();
        $qb->select('t')
                ->from('NumaDOAAdminBundle:ListingfieldTree', 't')
                //->join('NumaDOAAdminBundle:Listingfield', 'l')
                ->where('t.listing_field_id=:fieldid')
                ->andWhere('t.parent=0')
                //->andWhere('t.caption like :property')
                ->setParameter('fieldid', $fieldId);
        ;

        //$res = $query; //->getResult();
        ;
        return $qb;
    }

}
