setting:
    path:     /
    defaults: { _controller: "NumaDOASettingsBundle:Setting:index" }

setting_show:
    path:     /{id}/show
    defaults: { _controller: "NumaDOASettingsBundle:Setting:show" }

setting_new:
    path:     /new
    defaults: { _controller: "NumaDOASettingsBundle:Setting:new" }

setting_create:
    path:     /create
    defaults: { _controller: "NumaDOASettingsBundle:Setting:create" }
    requirements: { _method: post }

setting_edit:
    path:     /{id}/edit
    defaults: { _controller: "NumaDOASettingsBundle:Setting:edit" }

setting_update:
    path:     /{id}/update
    defaults: { _controller: "NumaDOASettingsBundle:Setting:update" }
    requirements: { _method: post|put }

setting_delete:
    path:     /{id}/delete
    defaults: { _controller: "NumaDOASettingsBundle:Setting:delete" }
    requirements: { _method: post|delete }

setting_cache_clear:
    path:     /cache_clear
    defaults: { _controller: "NumaDOASettingsBundle:Setting:clearCache" }
setting_cover_images:
    path:     /cover_images
    defaults: { _controller: "NumaDOASettingsBundle:Setting:makeCoverImages" }
setting_kijiji_all:
    path:     /kijiji_all
    defaults: { _controller: "NumaDOASettingsBundle:Setting:makeKijijiAll" }
setting_kijiji_current:
    path:     /kijiji_current
    defaults: { _controller: "NumaDOASettingsBundle:Setting:makeKijijiCurrent" }
setting_hometabs_refresh:
    path:     /hometabs_refresh
    defaults: { _controller: "NumaDOASettingsBundle:Setting:refreshHometabs" }
elasticksearch_populate:
    path:     /elasticksearch populate
    defaults: { _controller: "NumaDOASettingsBundle:Setting:populate" }
elasticksearch_start:
    path:     /elasticksearch_start
    defaults: { _controller: "NumaDOASettingsBundle:Setting:startElasticSearch" }
archiveItems:
    path:     /archive_items
    defaults: { _controller: "NumaDOASettingsBundle:Setting:archiveItems" }
setSoldDateItems:
    path:     /set_sold_date_items
    defaults: { _controller: "NumaDOASettingsBundle:Setting:setSoldDateItems" }