setting:
    path:     /
    defaults: { _controller: "NumaDOASettingsBundle:Setting:index" }

setting_show:
    path:     /{id}/show
    defaults: { _controller: "NumaDOASettingsBundle:Setting:show" }

setting_new:
    path:     /new
    defaults: { _controller: "NumaDOASettingsBundle:Setting:new" }

setting_create:
    path:     /create
    defaults: { _controller: "NumaDOASettingsBundle:Setting:create" }
    requirements: { _method: post }

setting_edit:
    path:     /{id}/edit
    defaults: { _controller: "NumaDOASettingsBundle:Setting:edit" }

setting_update:
    path:     /{id}/update
    defaults: { _controller: "NumaDOASettingsBundle:Setting:update" }
    requirements: { _method: post|put }

setting_delete:
    path:     /{id}/delete
    defaults: { _controller: "NumaDOASettingsBundle:Setting:delete" }
    requirements: { _method: post|delete }

setting_cache_clear:
    path:     /cache_clear
    defaults: { _controller: "NumaDOASettingsBundle:Setting:clearCache" }