Numa\DOAModuleBundle\Entity\Ad:
    type: entity
    table: ad
    #repositoryClass: Numa\DOAAdminBundle\Repository\AdRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            nullable: true
        title:
            type: string
            length: 255
            nullable: true
        position:
            type: string
            length: 255
            nullable: true
        status:
            type: string
            length: 255
            nullable: true
        size:
            type: string
            length: 255
            nullable: true
        photo:
            type: string
            length: 255
            nullable: true
        discount:
            type: float
            nullable: true    
        body:
            type: text
            nullable: true
        createdAt:
            type: datetime
            nullable: true
        updatedAt:
            type: datetime
            nullable: true;
    oneToMany:
        PageAds:
            targetEntity: PageAds
            mappedBy: Pages
            cascade: [persist]
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]