Numa\DOAModuleBundle\Entity\Ad:
    type: entity
    table: ad
    exclusion_policy: all
    repositoryClass: Numa\DOAModuleBundle\Repository\AdsRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            nullable: true
        title:
            type: string
            length: 255
            nullable: true
        position:
            type: string
            length: 255
            nullable: true
        status:
            type: string
            length: 255
            nullable: true
        size:
            type: string
            length: 255
            nullable: true
        photo:
            type: string
            length: 255
            nullable: true
        url:
            type: string
            length: 255
            nullable: true
        adorder:
            type: integer
            nullable: true
        discount:
            type: float
            nullable: true
        clicks:
            type: integer
            nullable: true
            options:
                default: 0
        views:
            type: integer
            nullable: true
            options:
                default: 0
        body:
            type: text
            nullable: true
        start_date:
            type: datetime
            nullable: true;
        end_date:
            type: datetime
            nullable: true;
        createdAt:
            type: datetime
            nullable: true
        updatedAt:
            type: datetime
            nullable: true;
        dealer_id:
             type: integer
             nullable: true
    oneToMany:
        PageAds:
            targetEntity: PageAds
            mappedBy: Ad
            cascade: [persist]
    manyToOne:
        Catalogrecords:
            targetEntity: Numa\DOAAdminBundle\Entity\Catalogrecords
            inversedBy: Ad
            joinColumn:
                name: dealer_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]