Numa\DOAModuleBundle\Entity\PageComponent:
    type: entity
    table: page_component
    repositoryClass: Numa\DOAModuleBundle\Repository\PageComponentRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        page_id:
            type: integer
        component_id:
            type: integer
    manyToOne:
        Page:
            targetEntity: Page
            cascade: [persist]
            inversedBy: Component
            joinColumn:
                name: page_id
                referencedColumnName: id
                onDelete: CASCADE
        Component:
            targetEntity: Component
            cascade: [persist,remove]
            inversedBy: Page
            onDelete: [cascade]
            orphanRemoval: true
            joinColumn:
                name: component_id
                onDelete: CASCADE
                referencedColumnName: id
                orphanRemoval: true
