Numa\DOAModuleBundle\Entity\Page:
    type: entity
    table: page
    repositoryClass: Numa\DOAModuleBundle\Repository\PageRepository
    indexes:
        url:
            columns: [ url ]
#        table_id:
#            columns: [ table_id ]
#        table_id:
#           columns: [ table_name,gittable_id ]

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        description:
            type: text
            nullable: true
        keywords:
            type: string
            length: 1024
            nullable: true
        title:
            type: string
            length: 512
            nullable: true
        url:
            type: string
            length: 512
            nullable: true
        is_public:
            type: boolean
            nullable: true
        autogenerate:
            type: boolean
            options:
               default: true
            nullable: true
        active:
            type: boolean
            options:
               default: true
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true

    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
    oneToMany:
        PageAds:
            targetEntity: PageAds
            mappedBy: Page
            cascade: [persist]
#    oneToOne:
#        Seo:
#            targetEntity: Numa\DOAModuleBundle\Entity\Seo
#            cascade: ["persist","remove"]
#            joinColumn:
#                name: seo_id
#                referencedColumnName: id