Numa\DOAModuleBundle\Entity\Seo:
    type: entity
    table: seo
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        description:
            type: text
            nullable: true
        keywords:
            type: string
            length: 1024
            nullable: true
        title:
            type: string
            length: 512
            nullable: true
        url:
            type: string
            length: 512
            nullable: true
        is_public:
            type: boolean
            nullable: true
        autogenerate:
            type: boolean
            options:
               default: true
            nullable: true
        active:
            type: boolean
            options:
               default: true
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]