dms_home:
    path:  /
    defaults: { _controller: "NumaDOADMSBundle:Default:index" }
dms_profile_edit:
    pattern:  /profile/{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:edit" }
dms_inventory_feeds:
    pattern:  /feeds
    defaults: { _controller: "NumaDOADMSBundle:Default:feeds" }
dms_customer:
    resource: "@NumaDOADMSBundle/Resources/config/routing/customer.yml"
    prefix:   /customers
dms_customer_switch:
    defaults: { _controller: "NumaDOADMSBundle:Default:dealerChooser" }
    path:   /customers_switch
dms_themes:
    defaults: { _controller: "NumaDOADMSBundle:Default:themes" }
    path:   /themes
dms_user:
    resource: "@NumaDOADMSBundle/Resources/config/routing/user.yml"
    prefix:   /users
dms_inventory:
    resource: "@NumaDOADMSBundle/Resources/config/routing/inventory.yml"
    prefix:   /inventory
dms_user_group:
    resource: "@NumaDOADMSBundle/Resources/config/routing/user_groups.yml"
    prefix:   /users_groups
NumaDOADMSBundle_partrequest:
    resource: "@NumaDOADMSBundle/Resources/config/routing/partrequest.yml"
    prefix:   /partrequest

NumaDOADMSBundle_client:
    resource: "@NumaDOADMSBundle/Resources/config/routing/client.yml"
    prefix:   /client

NumaDOADMSBundle_note:
    resource: "@NumaDOADMSBundle/Resources/config/routing/note.yml"
    prefix:   /note
NumaDOADMSBundle_billing:
    resource: "@NumaDOADMSBundle/Resources/config/routing/billing.yml"
    prefix:   /billing
NumaDOADMSBundle_dmsuser:
    resource: "@NumaDOADMSBundle/Resources/config/routing/dmsuser.yml"
    prefix:   /dmsuser
NumaDOADMSBundle_reminder:
    resource: "@NumaDOADMSBundle/Resources/config/routing/reminder.yml"
    prefix:   /reminder
dms_settings:
    resource: "@NumaDOADMSBundle/Resources/config/routing/settings.yml"
    prefix:   /settings
part_reguest:
    resource: "@NumaDOADMSBundle/Resources/config/routing/partrequest.yml"
    prefix:   /partreguest
dms_imageCarousel:
    resource: "@NumaDOADMSBundle/Resources/config/routing/imageCarousel.yml"
    prefix:   /imagecarousel
NumaDOADMSBundle_servicerequest:
    resource: "@NumaDOADMSBundle/Resources/config/routing/servicerequest.yml"
    prefix:   /servicerequest