dms_home:
    path:  /
    defaults: { _controller: "NumaDOADMSBundle:Default:index" }
dms_profile_edit:
    path:  /profile/{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:edit",_dashboard:"DMS" }
dms_inventory_feeds:
    path:  /feeds
    defaults: { _controller: "NumaDOADMSBundle:Default:feeds" }
dms_models:
    path:  /models
    defaults: { _controller: "NumaDOADMSBundle:Default:models" }
dms_customer:
    resource: "@NumaDOADMSBundle/Resources/config/routing/customer.yml"
    prefix:   /customers
dms_customer_switch:
    defaults: { _controller: "NumaDOADMSBundle:Default:dealerChooser" }
    path:   /customers_switch
dms_themes:
    defaults: { _controller: "NumaDOADMSBundle:Default:themes" }
    path:   /themes
dms_change_themes:
    defaults: { _controller: "NumaDOADMSBundle:Default:changeTheme" }
    path:   /change_themes
dms_user:
    resource: "@NumaDOADMSBundle/Resources/config/routing/user.yml"
    prefix:   /users
dms_inventory:
    resource: "@NumaDOADMSBundle/Resources/config/routing/inventory.yml"
    prefix:   /inventory
dms_user_group:
    resource: "@NumaDOADMSBundle/Resources/config/routing/user_groups.yml"
    prefix:   /users_groups
NumaDOADMSBundle_partrequest:
    resource: "@NumaDOADMSBundle/Resources/config/routing/partrequest.yml"
    prefix:   /partrequest
NumaDOADMSBundle_client:
    resource: "@NumaDOADMSBundle/Resources/config/routing/client.yml"
    prefix:   /client
NumaDOADMSBundle_note:
    resource: "@NumaDOADMSBundle/Resources/config/routing/note.yml"
    prefix:   /note
NumaDOADMSBundle_billing:
    resource: "@NumaDOADMSBundle/Resources/config/routing/billing.yml"
    prefix:   /billings
NumaDOADMSBundle_dmsuser:
    resource: "@NumaDOADMSBundle/Resources/config/routing/dmsuser.yml"
    prefix:   /dmsuser
userprofile_edit:
    path:     userprofile/{id}/edit
    defaults: { _controller: "NumaDOADMSBundle:DMSUser:edit" }
userprofile_update:
    path:     userprofile/{id}/update
    defaults: { _controller: "NumaDOADMSBundle:DMSUser:update" }
    requirements: { _method: post|put }

NumaDOADMSBundle_reminder:
    resource: "@NumaDOADMSBundle/Resources/config/routing/reminder.yml"
    prefix:   /reminders
dms_settings:
    resource: "@NumaDOADMSBundle/Resources/config/routing/settings.yml"
    prefix:   /settings
part_request:
    resource: "@NumaDOADMSBundle/Resources/config/routing/partrequest.yml"
    prefix:   /partrequest
dms_imageCarousel:
    resource: "@NumaDOADMSBundle/Resources/config/routing/imageCarousel.yml"
    prefix:   /imagecarousel
NumaDOADMSBundle_servicerequest:
    resource: "@NumaDOADMSBundle/Resources/config/routing/servicerequest.yml"
    prefix:   /servicerequest
dms_pages:
    resource: "@NumaDOADMSBundle/Resources/config/routing/pages.yml"
    prefix:   /pages
dms_component:
    resource: "@NumaDOADMSBundle/Resources/config/routing/component.yml"
    prefix:   /component
NumaDOADMSBundle_listingform:
    resource: "@NumaDOADMSBundle/Resources/config/routing/listingform.yml"
    prefix:   /listingform
NumaDOAAdminBundle_importfeed:
    resource: "@NumaDOADMSBundle/Resources/config/routing/importfeed.yml"
    prefix:   /featuredimport
NumaDOAAdminBundle_import_mapping:
    resource: "@NumaDOADMSBundle/Resources/config/routing/importmapping.yml"
    prefix:   /import_mapping
command_log:
    resource: "@NumaDOADMSBundle/Resources/config/routing/command_log.yml"
    prefix:   /command_log
NumaDOAAdminBundle_catalogs:
    resource: "@NumaDOADMSBundle/Resources/config/routing/catalogrecords.yml"
    prefix:   /catalogs
NumaDOADMSBundle_dealercomponent:
    resource: "@NumaDOADMSBundle/Resources/config/routing/dealercomponent.yml"
    prefix:   /dealercomponent
dms_reports:
    resource: "@NumaDOADMSBundle/Resources/config/routing/reports.yml"
    prefix:   /reports
NumaDOADMSBundle_finance:
    resource: "@NumaDOADMSBundle/Resources/config/routing/finance.yml"
    prefix:   /finance
NumaDOADMSBundle_vendor:
    resource: "@NumaDOADMSBundle/Resources/config/routing/vendor.yml"
    prefix:   /vendor
NumaDOADMSBundle_sale:
    resource: "@NumaDOADMSBundle/Resources/config/routing/sale.yml"
    prefix:   /sales
NumaDOADMSBundle_supportform:
    resource: "@NumaDOADMSBundle/Resources/config/routing/supportform.yml"
    prefix:   /supportform
NumaDOADMSBundle_dealergroup:
    resource: "@NumaDOADMSBundle/Resources/config/routing/dealergroup.yml"
    prefix:   /dealergroup
NumaDOADMSBundle_help:
    resource: "@NumaDOADMSBundle/Resources/config/routing/help.yml"
    prefix:   /dealergroup
dms_ads:
    resource: "@NumaDOADMSBundle/Resources/config/routing/ad.yml"
    prefix:   /ads
NumaDOADMSBundle_dmssetting:
    resource: "@NumaDOADMSBundle/Resources/config/routing/dmssetting.yml"
    prefix:   /dmssetting
dms_sandbox:
    resource: "@NumaDOADMSBundle/Resources/config/routing/sandbox.yml"
    prefix:   /sandbox
dms_quickbooks:
    resource: "@NumaDOADMSBundle/Resources/config/routing/quickbooks.yml"
    prefix:   /qb
numa_qb:
    resource: "@NumaQBBundle/Resources/config/routing.yml"
    prefix:   /quickbooks