services:
    Numa.Reports:
        class: Numa\DOADMSBundle\Lib\Reports
        arguments:  [@service_container]
    Numa.UiGrid:
        class: Numa\DOADMSBundle\Lib\UiGrid
        arguments:  [@service_container]
    Numa.DMSUtils:
        class: Numa\DOADMSBundle\Lib\DMSUtils
        arguments:  [@service_container]
    Numa.Dms.Listing:
        class: Numa\DOADMSBundle\Util\ListingLib
        arguments:  [@service_container]
    Numa.Dms.Sale:
        class: Numa\DOADMSBundle\Util\SaleLib
        arguments:  [@service_container]