parameters:
#    numa_doadms.example.class: Numa\DOADMSBundle\Example

services:
#    numa_doadms.example:
#        class: %numa_doadms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
