services:
    numa.reports:
        class: Numa\DOADMSBundle\Lib\ReportService
        arguments:  ["@service_container"]
    numa.uigrid:
        class: Numa\DOADMSBundle\Lib\UiGrid
        arguments:  ["@service_container"]
    numa.dmsutils:
        class: Numa\DOADMSBundle\Lib\DMSUtils
        arguments:  ["@service_container"]
    numa.dms.listing:
        class: Numa\DOADMSBundle\Util\ListingLib
        arguments:  ["@service_container"]
    numa.dms.dealer:
        class: Numa\DOADMSBundle\Util\DealerLib
        arguments:  ["@service_container"]
    numa.dms.customer:
        class: Numa\DOADMSBundle\Util\CustomerLib
        arguments:  ["@service_container"]
    numa.dms.billing:
        class: Numa\DOADMSBundle\Util\BillingLib
        arguments:  ["@service_container"]
    numa.dms.sale:
        class: Numa\DOADMSBundle\Util\SaleLib
        arguments:  ["@service_container"]
    numa.dms.command.log:
        class: Numa\DOADMSBundle\Util\CommandLogLib
        arguments:  ["@service_container"]
    numa.dms.images:
        class: Numa\DOADMSBundle\Util\ImageLib
        arguments:  ["@service_container"]
    numa.dms.utils:
        class: Numa\DOADMSBundle\Util\UtilsLib
        arguments:  ["@service_container"]
    numa.dms.text:
        class: Numa\DOADMSBundle\Util\TextLib
        arguments:  ["@service_container"]
    numa.form.container_aware_type:
        class: Numa\DOADMSBundle\Form\ContainerAwareType
        calls:
          - [setContainer, ['@service_container']]
        tags:
            - { name: form.type, alias: 'container_aware' }
    google.captcha:
        class: Numa\DOADMSBundle\Util\GoogleCaptchaLib
        arguments:  ["@service_container"]
    numa.dms.quickbooks:
        class: Numa\DOADMSBundle\Util\QuickbooksLib
        arguments:  ["@service_container"]
    numa.dms.quickbooks.account:
        class: Numa\DOADMSBundle\Util\QuickbooksAccountLib
        arguments:  ["@service_container"]
    numa.dms.quickbooks.tax:
        class: Numa\DOADMSBundle\Util\QuickbooksTaxLib
        arguments:  ["@service_container"]
    numa.dms.quickbooks.sale:
        class: Numa\DOADMSBundle\Util\QuickbooksSaleLib
        arguments:  ["@service_container"]
    numa.dms.quickbooks.bill:
        class: Numa\DOADMSBundle\Util\QuickbooksBillLib
        arguments:  ["@service_container"]
    numa.dms.quickbooks.purchase.order:
        class: Numa\DOADMSBundle\Util\QuickbooksPurchaseOrderLib
        arguments:  ["@service_container"]
    numa.dms.quickbooks.item:
        class: Numa\DOADMSBundle\Util\QuickbooksItemLib
        arguments:  ["@service_container"]
    numa.dms.quickbooks.vendor:
        class: Numa\DOADMSBundle\Util\QuickbooksVendorLib
        arguments:  ["@service_container"]
    numa.dms.quickbooks.customer:
        class: Numa\DOADMSBundle\Util\QuickbooksCustomerLib
        arguments:  ["@service_container"]