#parameters:
#
#services:
#    user.listener:
#        class: Numa\DOAAdminBundle\Listeners\EntityListener
#        arguments: [@service_container]
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }
#            - { name: doctrine.event_listener, event: preUpdate }
#            - { name: doctrine.event_listener, event: postUpdate }
#            - { name: doctrine.event_listener, event: preFlush }
#            - { name: doctrine.event_listener, event: onFlush }