#listing:
#    type: rest
#    resource: Numa\DOAAdminBundle\Controller\ItemRESTController
#    defaults: {_format: xml}
ads_api:
        resource: "@NumaDOAApiBundle/Resources/config/routing/ad.yml"
        prefix:   /ads
customer_api:
        resource: "@NumaDOAApiBundle/Resources/config/routing/customer.yml"
        prefix:   /customer
listing:
    pattern:  /listing/{id}.{_format}
    defaults: { _controller: "NumaDOAApiBundle:ItemREST:listing",_format: "xml"}
    requirements: { _method: get }

listingByDealer:
    pattern:  /listings/{dealerid}/dealer.{_format}
    defaults: { _controller: "NumaDOAApiBundle:ItemREST:listingsByDealer",_format: "xml"}
    requirements: { _method: get }

listingsAll:
    pattern:  /listings/{category}/category.{_format}
    defaults: { _controller: "NumaDOAApiBundle:ItemREST:listingsAll",_format: "xml"}
    requirements: { _method: get }

listingsAll:
    pattern:  /listings/{category}/category.{_format}
    defaults: { _controller: "NumaDOAApiBundle:ItemREST:listingsAll",_format: "xml"}
    requirements: { _method: get }