component_api_all:
    path:     /all.{_format}
    defaults: { _controller: "NumaDOAApiBundle:ComponentREST:all",_format: "json"}
    requirements: { _method: get }
component_by_page_api:
    path:     /{page_id}/page.{_format}
    defaults: { _controller: "NumaDOAApiBundle:ComponentREST:byPage",_format: "json"}
    requirements: { _method: get }
component_by_dealer_api:
    path:     /{dealer_id}/dealer.{_format}
    defaults: { _controller: "NumaDOAApiBundle:ComponentREST:byDealer",_format: "json"}
    requirements: { _method: get }
component_all_api:
    path:     /{dealer_id}/dealer_all.{_format}
    defaults: { _controller: "NumaDOAApiBundle:ComponentREST:allComponentsByDealer",_format: "json"}
    requirements: { _method: get }
