component_api_all:
    path:     /all.{_format}
    defaults: { _controller: "NumaDOAApiBundle:ComponentREST:all",_format: "json"}
    requirements: { _method: get }
component_by_dealer_api:
    path:     /{page_id}/page.{_format}
    defaults: { _controller: "NumaDOAApiBundle:ComponentREST:byPage",_format: "json"}
    requirements: { _method: get }
