notification_api_all:
    path:     /all.{_format}
    defaults: { _controller: "NumaDOAApiBundle:NotificationREST:all",_format: "json"}
    requirements: { method: get }
notification_by_dealer_api:
    path:     /{dealer_id}/dealer.{_format}
    defaults: { _controller: "NumaDOAApiBundle:NotificationREST:byDealer",_format: "json"}
    requirements: { method: get }
