part_request_api_all:
    path:     /all.{_format}
    defaults: { _controller: "NumaDOAApiBundle:PartRequestREST:all",_format: "json"}
    requirements: { _method: get }
part_request_by_dealer_api:
    path:     /{dealer_id}/dealer.{_format}
    defaults: { _controller: "NumaDOAApiBundle:PartRequestREST:byDealer",_format: "json"}
    requirements: { _method: get }
