service_request_api_all:
    path:     /all.{_format}
    defaults: { _controller: "NumaDOAApiBundle:ServiceRequestREST:all",_format: "json"}
    requirements: { _method: get }
service_request_by_dealer_api:
    path:     /{dealer_id}/dealer.{_format}
    defaults: { _controller: "NumaDOAApiBundle:ServiceRequestREST:byDealer",_format: "json"}
    requirements: { _method: get }
