parameters:
#    numa_doa_settings.example.class: Numa\DOASettingsBundle\Example

services:
#    numa_doa_settings.example:
#        class: %numa_doa_settings.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
