#listing:
#    type: rest
#    resource: Numa\DOAAdminBundle\Controller\ItemRESTController
#    defaults: {_format: xml}
listing:
    path:  /listing/{id}.{_format}
    defaults: { _controller: "NumaDOAAdminBundle:ItemREST:listing",_format: "xml"}
    requirements: { method: get }

listingByDealer:
    path:  /listings/{dealerid}/dealer.{_format}
    defaults: { _controller: "NumaDOAAdminBundle:ItemREST:listingsByDealer",_format: "xml"}
    requirements: { method: get }

listingsAll:
    path:  /listings/{category}/category.{_format}
    defaults: { _controller: "NumaDOAAdminBundle:ItemREST:listingsAll",_format: "xml"}
    requirements: { method: get }