catalogs:
    path:  /
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:index" }

catalogs_show:
    path:  /{id}/show
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:show" }

catalogs_new:
    path:  /new
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:new" }

catalogs_create:
    path:  /create
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:create" }
    requirements: { _method: post }

catalogs_edit:
    path:  /{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:edit" }

catalogs_update:
    path:  /{id}/update
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:update" }
    requirements: { _method: post|put }

catalogs_delete:
    path:  /{id}/delete
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:delete" }
    #requirements: { _method: post|delete }
catalog_import_csv:
    path:  /proccessCSV
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:proccessImportCSV" }
    requirements: { _method: post }
coupons_update:
    path:     /{id}/update_coupons
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:updateCoupons" }
    requirements: { _method: post|put }

catalogs_activate:
    path:  /{id}/activate
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:activateDealer" }
catalogs_update_fields:
    path:  /update_field
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:updateField" }
    requirements: { _method: post }