categories:
    path:  /
    defaults: { _controller: "NumaDOAAdminBundle:Category:index" }

categories_show:
    path:  /{id}/show
    defaults: { _controller: "NumaDOAAdminBundle:Category:show" }

categories_new:
    path:  /new
    defaults: { _controller: "NumaDOAAdminBundle:Category:new" }

categories_create:
    path:  /create
    defaults: { _controller: "NumaDOAAdminBundle:Category:create" }
    requirements: { method: post }

categories_edit:
    path:  /{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:Category:edit" }

categories_update:
    path:  /{id}/update
    defaults: { _controller: "NumaDOAAdminBundle:Category:update" }
    requirements: { method: post|put }

categories_delete:
    path:  /{id}/delete
    defaults: { _controller: "NumaDOAAdminBundle:Category:delete" }
    requirements: { method: post|delete }
