command_log_home:
    path:  /
    defaults: { _controller: "NumaDOAAdminBundle:CommandLog:index" }
command_log_detail:
    path:  /details/{id}
    defaults: { _controller: "NumaDOAAdminBundle:CommandLog:details" }
command_log_start:
    path:  /start
    defaults: { _controller: "NumaDOAAdminBundle:CommandLog:start" }    