importfeed:
    path:  /feed
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:index" }
mapping:
    path:  /mapping
    defaults: { _controller: "NumaDOAAdminBundle:Mapping:index" }
mapping_feed:
    path:  /mapping/{id}
    defaults: { _controller: "NumaDOAAdminBundle:Mapping:mapping" }

importfeed_show:
    path:  /{id}/show
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:show" }

importfeed_new:
    path:  /new
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:new" }

importfeed_create:
    path:  /create
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:create" }
    requirements: { method: post }

importfeed_edit:
    path:  /{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:edit" }

importfeed_update:
    path:  /{id}/update
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:update" }
    requirements: { method: post|put }

importfeed_delete:
    path:  /{id}/delete
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:delete" }
    requirements: { method: post|delete }
importfeed_items_delete:
    path:  /{id}/delete_items
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:deleteItems" }
