import_mapping:
    path:  /
    defaults: { _controller: "NumaDOAAdminBundle:Importmapping:index" }

import_mapping_show:
    path:  /{id}/show
    defaults: { _controller: "NumaDOAAdminBundle:Importmapping:show" }

import_mapping_new:
    path:  /new
    defaults: { _controller: "NumaDOAAdminBundle:Importmapping:new" }

import_mapping_create:
    path:  /create
    defaults: { _controller: "NumaDOAAdminBundle:Importmapping:create" }
    requirements: { method: post }

import_mapping_edit:
    path:  /{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:Importmapping:edit" }

import_mapping_update:
    path:  /{id}/update
    defaults: { _controller: "NumaDOAAdminBundle:Importmapping:update" }
    requirements: { method: post|put }

import_mapping_delete:
    path:  /{id}/delete
    defaults: { _controller: "NumaDOAAdminBundle:Importmapping:delete" }
    requirements: { method: post|delete }
import_mapping_reset:
    path:  /{id}/reset
    defaults: { _controller: "NumaDOAAdminBundle:Importmapping:reset" }
    
import_mapping_feed:
    path:  /{id}/feed
    defaults: { _controller: "NumaDOAAdminBundle:Importmapping:feed" }

import_mapping_fetch:
    path:  /{id}/fetch
    defaults: { _controller: "NumaDOAAdminBundle:Importmapping:fetch" }
import_mapping_mapvalues:
    path:  /mapvalues
    defaults: { _controller: "NumaDOAAdminBundle:Importmapping:mapvalues" }
import_mapping_add_mapvalues:
    path:  /addmapvalues
    defaults: { _controller: "NumaDOAAdminBundle:Importmapping:addMapValues" }
