itemfield:
    path:  /
    defaults: { _controller: "NumaDOAAdminBundle:ItemField:index" }

itemfield_show:
    path:  /{id}/show
    defaults: { _controller: "NumaDOAAdminBundle:ItemField:show" }

itemfield_new:
    path:  /new
    defaults: { _controller: "NumaDOAAdminBundle:ItemField:new" }

itemfield_create:
    path:  /create
    defaults: { _controller: "NumaDOAAdminBundle:ItemField:create" }
    requirements: { method: post }

itemfield_edit:
    path:  /{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:ItemField:edit" }

itemfield_update:
    path:  /{id}/update
    defaults: { _controller: "NumaDOAAdminBundle:ItemField:update" }
    requirements: { method: post|put }

itemfield_delete:
    path:  /delete
    defaults: { _controller: "NumaDOAAdminBundle:ItemField:delete" }
    requirements: { method: post|delete }
