itemfield:
    pattern:  /
    defaults: { _controller: "NumaDOAAdminBundle:ItemField:index" }

itemfield_show:
    pattern:  /{id}/show
    defaults: { _controller: "NumaDOAAdminBundle:ItemField:show" }

itemfield_new:
    pattern:  /new
    defaults: { _controller: "NumaDOAAdminBundle:ItemField:new" }

itemfield_create:
    pattern:  /create
    defaults: { _controller: "NumaDOAAdminBundle:ItemField:create" }
    requirements: { _method: post }

itemfield_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:ItemField:edit" }

itemfield_update:
    pattern:  /{id}/update
    defaults: { _controller: "NumaDOAAdminBundle:ItemField:update" }
    requirements: { _method: post|put }

itemfield_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "NumaDOAAdminBundle:ItemField:delete" }
    requirements: { _method: post|delete }
