items:
    path:  /
    defaults: { _controller: "NumaDOADMSBundle:Inventory:index" }

items_show:
    path:  /{id}/show
    defaults: { _controller: "NumaDOAAdminBundle:Item:show" }

items_new:
    path:  /{cat_id}/new
    defaults: { _controller: "NumaDOAAdminBundle:Item:new" }

additem:
    path:  /additem
    defaults: { _controller: "NumaDOAAdminBundle:Item:additem" }

items_create:
    path:  /create
    defaults: { _controller: "NumaDOAAdminBundle:Item:create" }
    requirements: { method: post }
item_category_change:
    path:  /{id}/category
    defaults: { _controller: "NumaDOAAdminBundle:Item:changeCategory" }
    requirements: { method: post|put }

items_edit:
    path:  /{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:Item:edit" }

items_update:
    path:  /{id}/update
    defaults: { _controller: "NumaDOAAdminBundle:Item:update" }
    requirements: { method: post|put }

items_delete:
    path:  /{id}/delete
    defaults: { _controller: "NumaDOAAdminBundle:Item:delete" }

items_activate:
    path:  /{id}/activate
    defaults: { _controller: "NumaDOAAdminBundle:Item:activate" }
items_deactivate:
    path:  /{id}/deactivate
    defaults: { _controller: "NumaDOAAdminBundle:Item:deactivate" }
items_reject:
    path:  /{id}/approve
    defaults: { _controller: "NumaDOAAdminBundle:Item:reject" }
items_approve:
    path:  /{id}/reject
    defaults: { _controller: "NumaDOAAdminBundle:Item:approve" }
item_images:
    path: /{id}/images
    defaults: { _controller: "NumaDOAAdminBundle:Image:show" }
item_images_upload:
    path: /{id}/imagesupload
    defaults: { _controller: "NumaDOAAdminBundle:Image:upload" }
    requirements: { id: \d+ }
item_image_setorder:
    path: /image_order
    defaults: { _controller: "NumaDOAAdminBundle:Image:setImageOrder" }
    condition: "request.isXmlHttpRequest()"
item_images_add_video:
    path: /{id}/addvideo
    defaults: { _controller: "NumaDOAAdminBundle:Image:addVideo" }
    requirements: { id: \d+ }