user:
    path:  /
    defaults: { _controller: "NumaDOAAdminBundle:User:index" }

user_show:
    path:  /{id}/show
    defaults: { _controller: "NumaDOAAdminBundle:User:show" }

user_new:
    path:  /new
    defaults: { _controller: "NumaDOAAdminBundle:User:new" }

user_create:
    path:  /create
    defaults: { _controller: "NumaDOAAdminBundle:User:create" }
    requirements: { method: post }

user_edit:
    path:  /{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:User:edit" }

user_update:
    path:  /{id}/update
    defaults: { _controller: "NumaDOAAdminBundle:User:update" }

user_delete:
    path:  /{id}/delete
    defaults: { _controller: "NumaDOAAdminBundle:User:delete" }
    requirements: { method: get|post|delete }
