Numa\DOAAdminBundle\Entity\Catalogrecords:
    type: entity
    table: catalog_records
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        category_id:
            type: integer
        description:
            type: text
        url:
            type: string
            length: 255
        address:
            type: string
            length: 255

        phone:
            type: string
            length: 255

        location:
            type: string
            length: 255

        email:
            type: string
            length: 255
        fax:
            type: string
            length: 255
        full:
            type: text
        
        
    manyToOne:
        CatalogCategory:
            targetEntity: CatalogCategory
            inversedBy: CatalogRecords
            joinColumn:
                name: category_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]