Numa\DOAAdminBundle\Entity\Catalogcategory:
    type: entity
    table: catalog_category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
        slug:
            type: string
            length: 255
            unique: true
    oneToMany:
        CatalogRecords:
            targetEntity: CatalogRecords
            mappedBy: catalogcategories