Numa\DOAAdminBundle\Entity\Catalogrecords:
    type: entity
    table: catalog_records
    repositoryClass: Numa\DOAAdminBundle\Repository\CatalogrecordsRepository
    indexes:
            site_url:
                columns: [ site_url ]
            username:
                columns: [ username ]
            email:
                columns: [ email ]
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            nullable: true
        username:
            type: string
            length: 255
            nullable: true
        category_id:
            type: integer
            nullable: true
        dealer_group_id:
            type: integer
            nullable: true
        description:
            type: text
            nullable: true
        url:
            type: string
            length: 255
            nullable: true
        address:
            type: string
            length: 255
            nullable: true
        phone:
            type: string
            length: 255
            nullable: true
        location:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        finance_email:
            type: string
            length: 255
            nullable: true
        fax:
            type: string
            length: 255
            nullable: true
        full:
            type: text
            nullable: true
        logo:
            type: string
            length: 255
            nullable: true
        logo_url:    
            type: string
            length: 255
            nullable: true
        terms_upload:
            type: string
            length: 255
            nullable: true
        terms_text:
            type: text
            nullable: true
        password:
            type: string
            length: 255
            nullable: true
        contact:
            type: string
            length: 255
            nullable: true
        dealer_id:
            type: string
            length: 255
            nullable: true
        dealer_number:
            type: string
            length: 255
            nullable: true
        address2:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        zip:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: 255
            nullable: true
        state:
            type: string
            length: 255
            nullable: true
        ShowRoomHours:
            type: text
            nullable: true
        ServiceHours:
            type: text
            nullable: true
        PartsHours:
            type: text
            nullable: true            
        AdminHours:
            type: text
            nullable: true
        Admindealer:
            type: boolean
            nullable: true
        dms_status:
            type: string
            length: 255
            nullable: true
        gst:
            type: string
            length: 255
            nullable: true
        site_url:
            type: string
            length: 255
            nullable: true
        site_theme:
            type: string
            length: 255
            nullable: true
        site_facebook:
            type: string
            length: 255
            nullable: true
        site_youtube:
            type: string
            length: 255
            nullable: true
        site_google:
            type: string
            length: 255
            nullable: true
        site_twitter:
            type: string
            length: 255
            nullable: true
        site_instagram:
            type: string
            length: 255
            nullable: true
        site_googlemap:
            type: string
            length: 511
            nullable: true
        site_google_tag:
            type: string
            length: 255
            nullable: true
        site_facebook_pixel_id:
            type: string
            length: 255
            nullable: true
        default_listing_comment:
            type: text
            nullable: true
        fuel_economy:
            type: string
            length: 255
            nullable: true
        feed_kijiji_url:
            type: string
            length: 255
            nullable: true
        feed_kijiji_username:
            type: string
            length: 255
            nullable: true
        feed_kijiji_password:
            type: string
            length: 255
            nullable: true
        feed_kijiji_manual:
            type: boolean
            nullable: true
        setting_purechat:
            type: text
            nullable: true
        setting_ga:
            type: string
            length: 255
            nullable: true
        setting_ga_view:
            type: string
            length: 255
            nullable: true
        qb_realm_id:
            type: string
            length: 255
            nullable: true
        qb_identifier:
            type: string
            length: 255
            nullable: true
        qb_identifier:
            type: string
            length: 255
            nullable: true
        qb_token_credential:
            type: text
            nullable: true
        qb_temp_token:
            type: text
            nullable: true
        qb_server:
            type: text
            nullable: true
        legal_trade_name:
            type: string
            length: 255
            nullable: true
        biweekly_url:
            type: string
            length: 255
            nullable: true
    manyToOne:
        Catalogcategory:
            targetEntity: Catalogcategory
            inversedBy: Catalogrecords
            joinColumn:
                name: category_id
                referencedColumnName: id
        DealerGroup:
            targetEntity: Numa\DOADMSBundle\Entity\DealerGroup
            inversedBy: Dealer
            joinColumn:
                name: dealer_group_id
                referencedColumnName: id
    oneToMany:
        DealerCategories:
            targetEntity: DealerCategories
            mappedBy: Catalogrecords
            cascade: [persist]
        Coupon:
            targetEntity: Coupon
            mappedBy: Catalogrecords
            cascade: [persist]
        Component:
            targetEntity: Numa\DOADMSBundle\Entity\DealerComponent
            mappedBy: Dealer
            cascade: [persist]
        HomeTab:
            targetEntity: Numa\DOAAdminBundle\Entity\HomeTab
            mappedBy: Catalogrecords
            cascade: [persist]
        DealerSetting:
            targetEntity: Numa\DOADMSBundle\Entity\DealerSetting
            mappedBy: Dealer
            cascade: [persist]
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]