Numa\DOAAdminBundle\Entity\HomeTab:
    type: entity
    table: home_tab
    repositoryClass: Numa\DOAAdminBundle\Repository\HomeTabRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        category_id:
            type: integer
            nullable: true
        dealer_id:
            type: integer
            nullable: true
        category_name:
            type: string
            length: 255
            nullable: true
        listing_field_list_id:
            type: integer
            nullable: true
        listing_field_list_value:
            type: string
            length: 255
            nullable: true
        listing_field_list_slug:
            type: string
            length: 255
            nullable: true
        position:
            type: integer
            nullable: true
        count:
            type: integer
            nullable: true
        is_public:
            type: boolean
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
    manyToOne:
        Category:
            targetEntity: Category
            joinColumn:
                name: category_id
                referencedColumnName: id
        ListingFieldLists:
            targetEntity: ListingFieldLists
            joinColumn:
                name: listing_field_list_id
                referencedColumnName: id
        Dealer:
            targetEntity: Numa\DOAAdminBundle\Entity\Catalogrecords
            joinColumn:
                name: dealer_id
                referencedColumnName: id