Numa\DOAAdminBundle\Entity\ImageCarousel:
    type: entity
    table: imiage_carousel
    repositoryClass: Numa\DOAAdminBundle\Repository\ImageCarouselRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        src:
            type: string
            length: 255
            nullable: true
        title:
            type: string
            length: 255
            nullable: true
        url:
            type: string
            length: 255
            nullable: true
        position:
            type: integer
            nullable: true
        count:
            type: integer
            nullable: true
        is_public:
            type: boolean
            nullable: true
        active:
            type: boolean
            options:
               default: true
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
        dealer_id:
            type: integer
            nullable: true
        component_id:
            type: integer
            nullable: true
    manyToOne:
        Dealer:
            targetEntity: Numa\DOAAdminBundle\Entity\Catalogrecords
            joinColumn:
                name: dealer_id
                referencedColumnName: id
        Component:
            targetEntity: Numa\DOAModuleBundle\Entity\Component
            joinColumn:
                name: component_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]