Numa\DOAAdminBundle\Entity\Listingfield:
    type: entity
    repositoryClass: Numa\DOAAdminBundle\Entity\ListingfieldRepository
    table: listing_field
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
      sid:                                     
            type: string
            length: 255
            unique: true
      category_sid:
            type: integer
      order:
            type: integer
      caption:                                     
            type: string
            length: 255
            nullable: true
      type:                                     
            type: string
            length: 255
            nullable: true
      is_required:                                     
            type: boolean
      minimum:                                     
            type: string
            length: 255
            nullable: true
      maximum:                                     
            type: string
            length: 255
            nullable: true
      signs_num:
            type: integer
            nullable: true
      maxlength:                                     
            type: string
            length: 255
            nullable: true
      max_file_size:                                     
            type: string
            length: 255
            nullable: true
      levels_ids:                                     
            type: string
            length: 255
            nullable: true
      levels_captions:                                     
            type: string
            length: 255
            nullable: true
      item_field_caption:
            type: string
            length: 255
            nullable: true
      api_caption:
            type: string
            length: 255
            nullable: true
      exclude_from_api:
            type: boolean
            nullable: true
            default: false;
    oneToMany:
        Importmapping:
            targetEntity: Importmapping
            mappedBy: Listingfield
        ItemField:
            targetEntity: ItemField
            mappedBy: Listingfield
        ListingFieldLists:
            targetEntity: ListingFieldLists
            mappedBy: Listingfield