##  sid 	field_sid Descending 	parent_sid 	level 	order 	caption 
Numa\DOAAdminBundle\Entity\ListingFieldTree:
    type: entity
    repositoryClass: Numa\DOAAdminBundle\Repository\ListingFieldTreeRepository
    table: listing_field_tree
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
      listing_field_id:                                     
            type: integer
            nullable: true
      parent_id:                                     
            type: integer
            nullable: true
      order:
            type: integer
            nullable: true
      level:                                     
            type: integer
            nullable: true
      name:                                     
            type: string
            length: 255
            nullable: true
    oneToMany:
      children:
            targetEntity: ListingFieldTree
            mappedBy: parent
    manyToOne:
      parent:
            targetEntity: ListingFieldTree
            inversedBy: children
             
