Numa\DOAAdminBundle\Entity\UserSearch:
    type: entity
    table: user_search
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:        
        user_id:
            type: integer
            nullable: true        
        active:
            type: boolean
            default: 0
            nullable: true 
        search_type:
            type: integer
            nullable: true 
            default: 0;  
        search_url:
            type: string
            nullable: true 
        name:
            type: string
            nullable: true 
        date_created:
            type: datetime
            nullable: true            
        date_updated:
            type: datetime
            nullable: true
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ] 
    manyToOne:
        User:
            targetEntity: User
            inversedBy: UserSearch
            joinColumn:
                name: user_id
                referencedColumnName: id   