imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
parameters:
    email_from: general@dealersonair.com
monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  warning
        console:
            type:   console
            path:   "%kernel.logs_dir%/console_%kernel.environment%.log"
            level:  warning