imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    
services:
    memcached:
        class: Memcached
        calls:
            - [ addServers, [ %memcached.servers% ]]
#        "endroid/qrcode-bundle": "dev-master",nelmio_api_doc: ~    
#lsw_memcache:
#    session:
#        pool: default
#    pools:
#        default:
#            servers:
#              - { host: localhost, tcp_port: 11212 }
#lsw_guzzle:
#    clients:
#        test:
#            config:
#                json_objects: true
#                curl.options:
#                    CURLOPT_CONNECTTIMEOUT: 10
#                    CURLOPT_SSL_VERIFYPEER: false
#                    CURLOPT_USERAGENT: "LeaseWeb API Caller"
#                    CURLOPT_FOLLOWLOCATION: true
#                    CURLOPT_SSLVERSION: 3              
framework:
    esi: { enabled: true }

    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~    
    fragments:       ~
    http_method_override: true
    session:
        handler_id: ~
    serializer:
         enable_annotations: true
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        title: CJVR Dealers On Air
        subject: Email from
        upload_feed_path: /upload/feeds/
#    form:
#        resources: ['bootstrap_3_horizontal_layout.html.twig']

# Assetic Configuration
assetic:
    debug: %kernel.debug%
    use_controller: false
    bundles: ['NumaDOASiteBundle','NumaDOAAdminBundle' ]
    filters:
        cssrewrite: ~
        less:
           node: /usr/local/bin/node
           node_paths: [/usr/local/lib/node_modules]
           apply_to: "\.less$"
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
#        yui_js:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"   
    assets:
        bootstrap:
            inputs:
               - '%kernel.root_dir%/../web/bootstrap3/css/bootstrap.min.css'        
        bootstrap_select_css:
            inputs:
               - '%kernel.root_dir%/../web/bootstrap3/select/css/bootstrap-select.min.css'        
        style:
            inputs:
               - '%kernel.root_dir%/../web/css/style.css'  
        admin:
            inputs:
               - '%kernel.root_dir%/../web/css/admin.css'
        jquery_ui_css:
            inputs:
               - '%kernel.root_dir%/../web/jqueryUI/css/ui-lightness/jquery-ui-1.10.3.custom.css'
        bx_slider_css:
            inputs:
               - '%kernel.root_dir%/../web/css/jquery.bxslider.css'
        flex_slider_css:
            inputs:
               - '%kernel.root_dir%/../web/flexSlider/flexslider.css'
        pgw_slideshow_css:
            inputs:
               - '%kernel.root_dir%/../web/css/pgwslideshow.css'
        dropzone_css:
            inputs:
               - '%kernel.root_dir%/../web/css/dropzone.css'
        colorbox_css:
            inputs:
               - '%kernel.root_dir%/../web/css/colorbox.css'
        AdminLTE_css:
            inputs:
               - '%kernel.root_dir%/../web/css/AdminLTE.min.css'
        AdminLTE_blue_skin_css:
            inputs:
               - '%kernel.root_dir%/../web/css/skins/skin-blue.css'

        #javascript



        bootstrapx_js:
            inputs:
                - '%kernel.root_dir%/../web/bootstrap3/js/bootstrap.min.js'
        bootstrap_select_js:
            inputs:
                - '%kernel.root_dir%/../web/bootstrap3/select/js/bootstrap-select.min.js'
        jquery_ui_js:
            inputs:
                - '%kernel.root_dir%/../web/jqueryUI/js/jquery-ui-1.10.3.custom.min.js'
                - '%kernel.root_dir%/../web/jqueryUI/js/jquery.ui.swappable.js'
        jquery_jssor_js:
            inputs:
                - '%kernel.root_dir%/../web/js/jssor/jssor.core.js'
                - '%kernel.root_dir%/../web/js/jssor/jssor.slider.js'
                - '%kernel.root_dir%/../web/js/jssor/jssor.utils.js'
        bx_slider_js:
            inputs:
                - '%kernel.root_dir%/../web/js/jquery.bxslider.js'
        flex_slider_js:
            inputs:
                - '%kernel.root_dir%/../web/flexSlider/jquery.flexslider.js'
        common_js:
            inputs:
                - '%kernel.root_dir%/../web/js/common.js'
        savecompared_js:
            inputs:
                - '%kernel.root_dir%/../web/js/savecomparead.js'
        tinymce_js:
            inputs:
                - '%kernel.root_dir%/../web/tinymce/js/tinymce/tinymce.min.js'
        pgw_slideshow_js:
            inputs:
                - '%kernel.root_dir%/../web/js/pgwslideshow.js'
        printElement:
            inputs:
                - '%kernel.root_dir%/../web/js/printElement.js'
        dropzone_js:
            inputs:
                - '%kernel.root_dir%/../web/js/dropzone.js'
        colorbox_js:
            inputs:
                - '%kernel.root_dir%/../web/js/jquery.colorbox-min.js'
        sortable_js:
            inputs:
                - '%kernel.root_dir%/../web/js/Sortable.min.js'
        AdminLTE_js:
            inputs:
                - '%kernel.root_dir%/../web/js/app.min.js'
# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        metadata_cache_driver: memcache
        query_cache_driver: memcache 
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        filters:
            active_filter: Numa\DOASiteBundle\Filters\ActiveFilter
        dql:
            string_functions:
                GroupConcat: DoctrineExtensions\Query\Mysql\GroupConcat

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

genemu_form:
    tinymce: 
        theme:   advanced
#comur_image:
#    config:
#        cropped_image_dir: 'cropped'
#        thumbs_dir: 'thumbnails'
#        media_lib_thumb_size: 150
#        web_dirname: 'web'
#        translation_domain: 'ComurImageBundle'
#        gallery_thumb_size: 150
#        gallery_dir: 'gallery'

liip_imagine:
    resolvers:
        default:
            web_path:
              web_root:  %kernel.root_dir%/../web
              cache_prefix: media/cache
    filter_sets:
        search_image:
            quality: 100
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
                background: { color: '#FFFFFF' }
        logo_image:
            quality: 100
            filters:
                thumbnail: { size: [200, 160], mode: inset }
                background: { color: '#FFFFFF' }
        item_detail_image:
            quality: 100
            filters:
                thumbnail: { size: [666, 480], mode: outbound }
                background: { color: '#FFFFFF' }
        home_tab:
            quality: 100
            filters:
                thumbnail: { size: [150, 100], mode: inset }
                background: { color: '#FFFFFF' }
        carousel:
            quality: 100
            filters:
#                thumbnail: { size: [605, 450], mode: inset }
#
                relative_resize: { widen: 606 }
                background: { color: '#FFFFFF' }
                #thumbnail: { size: [210, 140], mode: outbound }
parameters:
    upload_url: /upload/itemsimages
    web_path: %kernel.root_dir%/../web
    images_path: %kernel.root_dir%/../web/images
    upload_path: %kernel.root_dir%/../web/upload/itemsimages/
    upload_feed: %kernel.root_dir%/../web/upload/feeds/
    iauto: %kernel.root_dir%/../web/iauto
    memcached.servers:
      - { host: 127.0.0.1, port: 11211 }
    antispam_button:
        good: xuitybzerpidvfugvo
        bad:  kuserhxvvkigyhsdsf
    router.request_context.host: dev.dealersonair.com
    router.request_context.scheme: https
    #router.request_context.base_url: /
gregwar_image: ~  
endroid_qr_code:
    size: 100
    padding: 10
    extension: gif
    error_correction_level: high
    
apy_data_grid:
    pagerfanta:
        enable: true    #default false
        view_class: Pagerfanta\View\TwitterBootstrapView #default    Pagerfanta\View\DefaultView
        options:            #all options of pager fanta view constructor
           prev_message : «
           next_message : »        
trsteel_ckeditor:
    class: Trsteel\CkeditorBundle\Form\Type\CkeditorType
    toolbar: ['document', 'clipboard', 'editing', '/', 'basicstyles', 'paragraph', 'links', '/',  'styles', 'tools']
    toolbar_groups:
        document: ['Source']
genemu_form:
    captcha:
        enabled:          true
        width:            100
        height:           100
        length:           4
        format:           'png'
        chars:            '0123456789'
        font_size:        24
        font_color:       ['252525', '8B8787', '550707', '3526E6', '88531E']
        font_dir:         %kernel.root_dir%/../web/bundles/genemuform/fonts
        fonts:            [ 'whoobub.ttf']
        background_color: 'DDDDDD'
        border_color:     '000000'
        grayscale:        false

sensio_framework_extra:
        view:    {annotations: false}
        router:  {annotations: true}

fos_rest:
#        format_listener:
#             rules:
#                - prefer_extension: false
        view:
             view_response_listener: true
jms_serializer:
  metadata:
    auto_detection: true





#braincrafted_bootstrap:
#    output_dir:
#    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
#    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js
#    #less_filter: less # "less", "lessphp", "sass" or "none"
#    fonts_dir: %kernel.root_dir%/../web/fonts
#    auto_configure:
#        assetic: true
#        twig: true
#        knp_menu: true
#        knp_paginator: true
#    customize:
#        variables_file: ~
#        #bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
#        #bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig                
