fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            settings:
                index:
                    analysis:
                        analyzer:
                            string_lowercase:
                                tokenizer: keyword
                                filter: [ lowercase , trim ]
#                                char_filter: my_char_filter
#                        char_filter:
#                            my_char_filter:
#                                type: pattern_replace
#                                pattern: ["(\\w+) - (?=\\w)"]
#                                replacement": ["$1 "]
            types:
                Item:

                    mappings:
                        id:
                          type: integer
                        make:
                          analyzer: string_lowercase
                          type: string
                        model:
                          analyzer: string_lowercase
                          type: string
                        year:
                          type: integer
                        status: ~
                        type: ~
                        price:
                          type: integer
                        bi_weekly:
                          type: integer
                        retailPrice:
                          type: integer
                        active:
                          type : boolean
                        featured:
                          type : boolean
                        date_created:
                          type : date
                        dealer_id:
                          type: integer
                        dealerName: ~
                        dealerPhone: ~
                        category_id:
                          type: integer
                        categoryName: ~
                        categorySubType:
                          analyzer: string_lowercase
                          type: string

                        views: ~
                        VIN: ~
                        mileage:
                          type: integer
                        feed_id:
                          type: integer
                        trim: ~
                        stock_nr: ~
                        transmission: ~
                        iw_no: ~
                        sold: ~
                        bodyStyle: ~
                        fuelType: ~
                        interiorColor: ~
                        exteriorColor: ~
                        horsepower: ~
                        ofHours: ~
                        steering: ~
                        speedForward: ~
                        speedReverse: ~
                        tireSize: ~
                        tireEquipment: ~
                        cutting_width: ~
                        width: ~
                        beam: ~
                        hullDesign: ~
                        steeringType: ~
                        driveType: ~
                        fuelCapacity: ~
                        passengers: ~
                        trailer: ~
                        battery: ~
                        chassisType: ~
                        sleeps: ~
                        slideOuts: ~
                        flooring: ~
                        archiveStatus: ~
                        dealerGroup:
                            type: integer
                        coverImageSrc: ~
                        urlDescription: ~
                        title: ~
                        lastUpdated: ~
                        priceString: ~
                        retailPriceString: ~
                        length: ~
                        engine: ~
                        agApplication: ~
                        florpane: ~
                        bodyDescription: ~
                        truckVanType:
                            analyzer: string_lowercase
                            type: string

                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: Numa\DOAAdminBundle\Entity\Item
                        provider:
                            query_builder_method: createIsActiveNonDeletedQueryBuilder
                        listener:
                            insert: true
                            update: true
                            delete: true
                        finder: ~
                        repository: Numa\DOASiteBundle\Search\ItemRepository
