fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            types:
                Item:
                    mappings:
                        id:
                          type: integer
                        make:
                          index: not_analyzed
                          type: string
                        model:
                          index: not_analyzed
                          type: string
                        year:
                          type: integer
                        status: ~
                        type: ~
                        price:
                          type: integer
                        active:
                          type : boolean
                        featured:
                          type : boolean
                        date_created:
                          type : date
                        dealer_id:
                          type: integer
                        categoryName: ~
                        categorySubType:
                          index: not_analyzed
                          type: string
                        views: ~
                        VIN: ~
                        mileage:
                          type: integer
                        trim: ~
                        stock_nr: ~
                        transmission: ~
                        iw_no: ~
                        sold: ~
                        bodyStyle: ~
                        fuelType: ~
                        interiorColor: ~
                        exteriorColor: ~
                        horsepower: ~
                        ofHours: ~
                        steering: ~
                        speedForward: ~
                        speedReverse: ~
                        tireSize: ~
                        tireEquipment: ~
                        cutting_width: ~
                        width: ~
                        beam: ~
                        hullDesign: ~
                        steeringType: ~
                        driveType: ~
                        fuelCapacity: ~
                        passengers: ~
                        trailer: ~
                        battery: ~
                        chassisType: ~
                        sleeps: ~
                        slideOuts: ~
                        flooring: ~
                        dealerGroup:
                            type: integer

                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: Numa\DOAAdminBundle\Entity\Item
                        provider: ~
                        listener:
                          insert: true
                          update: true
                          delete: true
                        finder: ~