security:
    access_denied_url: /error/403
    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_BUSINES:    ROLE_BUSINES
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH,ROLE_BUSINES]
 
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /user/login
                check_path:  /login_check
                default_target_path: /admin/dashboard
                success_handler: login_success_handler
            logout:
                path:   /logout
                target: /
 
    access_control:
        - { path: ^/admin/items/*, roles: [ROLE_ADMIN, ROLE_BUSINES] }
        - { path: ^/admin/catalogs/*, roles: [ROLE_ADMIN, ROLE_BUSINES] }        
        - { path: ^/admin, roles: ROLE_ADMIN }
 
    providers:
        chain_provider:
            chain:
                providers: [main, busines]
        main:
            entity: { class: Numa\DOAAdminBundle\Entity\User, property: email }
        busines:
            entity: { class: Numa\DOAAdminBundle\Entity\Catalogrecords, property: username }
 
    encoders:
        Numa\DOAAdminBundle\Entity\User: sha512
        Numa\DOAAdminBundle\Entity\Catalogrecords: sha512