security:
    access_denied_url: /error/403
    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
 
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /user/login
                check_path:  /login_check
                default_target_path: /admin/dashboard
                success_handler: login_success_handler
            logout:
                path:   /logout
                target: /
 
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
 
    providers:
        main:
            entity: { class: Numa\DOAAdminBundle\Entity\User, property: email }
 
    encoders:
        Numa\DOAAdminBundle\Entity\User: sha512