security:
    access_denied_url: /error/403
    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_BUSINES:    ROLE_BUSINES
        ROLE_DEALER_ADMIN:    ROLE_DEALER_ADMIN
        ROLE_ADMIN:      ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH,ROLE_BUSINES,ROLE_DEALER_ADMIN]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /user/login
                check_path:  /login_check
                default_target_path: /admin
                success_handler: login_success_handler
            logout:
                path:   /logout
                target: /
 
    access_control:

        - { path: ^/admin/items/additem/, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/items/additem, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/itemsfield/[0-9]+/delete, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/itemsfield/[0-9]+/delete/, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/items/[0-9]+, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/catalogs/[0-9]+, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/items, roles: [ROLE_ADMIN,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/items/, roles: [ROLE_ADMIN,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/featuredimport, roles: [ROLE_ADMIN] }
        - { path: ^/admin/feed_api, roles: [ROLE_ADMIN] }
        - { path: ^/admin/categories, roles: [ROLE_ADMIN] }
        - { path: ^/admin/user_group, roles: [ROLE_ADMIN] }
        - { path: ^/admin/command_log, roles: [ROLE_ADMIN] }
        - { path: ^/admin/setting, roles: [ROLE_ADMIN] }
        - { path: ^/admin, roles: [ROLE_ADMIN,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/, roles: [ROLE_ADMIN,ROLE_DEALER_ADMIN] }



    providers:
        chain_provider:
            chain:
                providers: [main, busines]
        main:
            entity: { class: Numa\DOAAdminBundle\Entity\User, property: email }
        busines:
            entity: { class: Numa\DOAAdminBundle\Entity\Catalogrecords}
 
    encoders:
        Numa\DOAAdminBundle\Entity\User: sha512
        Numa\DOAAdminBundle\Entity\Catalogrecords: sha512