security:
    access_denied_url: /error/403
    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_BUSINES:    ROLE_BUSINES
        ROLE_DEALER_ADMIN:    ROLE_DEALER_ADMIN
        ROLE_DMS_USER:      ROLE_DMS_USER
        ROLE_ADMIN:      ROLE_ADMIN
        
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH,ROLE_BUSINES,ROLE_DEALER_ADMIN,ROLE_DMS_USER]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /user/login
                check_path:  /login_check
                default_target_path: /dms
                success_handler: login_success_handler
            logout:
                path:   /logout
                target: /
                success_handler: logout_success_handler
    access_control:

        - { path: ^/dms/users_groups, roles: [ROLE_ADMIN] }
        - { path: ^/dms/userprofile, roles: [ROLE_ADMIN,ROLE_DMS_USER,ROLE_ACCOUNTING,ROLE_SALES,ROLE_PARTS_DMS,ROLE_SERVICE_DMS,ROLE_FINANCE_DMS,ROLE_WHOLESALE_DMS,ROLE_SALES,ROLE_SALE2_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_REGULAR_ADMIN_DMS] }
        - { path: ^/dms/dmsuser, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/user, roles: [ROLE_ADMIN,ROLE_BUSINES] }
        - { path: ^/dms/dealergroup, roles: [ROLE_ADMIN,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/component, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_SALES, ROLE_SALE3_DMS, ROLE_SALE4_DMS] }
        - { path: ^/dms/pages, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_SALES, ROLE_SALE3_DMS, ROLE_SALE4_DMS] }
        - { path: ^/dms/profile, roles: [ROLE_ADMIN,ROLE_DMS_USER,ROLE_ACCOUNTING,ROLE_SALES, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_REGULAR_ADMIN_DMS] }
        - { path: ^/dms/finance, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_FINANCE_DMS,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS,ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/customer, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/vendor, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/listing_form, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES, ROLE_SALE4_DMS] }
        - { path: ^/dms/themes, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES,ROLE_SALE3_DMS, ROLE_SALE4_DMS ] }
        - { path: ^/dms/settings, roles: [ROLE_ADMIN,ROLE_DMS_USER] }
        - { path: ^/dms/image_carousel, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER, ROLE_SALE4_DMS] }
        - { path: ^/dms/command_log, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER] }
        - { path: ^/dms/reports, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_DEALER_PRINCIPAL,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS,ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_SALE2_DEALER_GROUP_DMS] }
        - { path: ^/dms/partrequest, roles: [ROLE_ADMIN,ROLE_DMS_USER,ROLE_ACCOUNTING,ROLE_SALES,ROLE_PARTS_DMS,ROLE_SERVICE_DMS,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS] }
        - { path: ^/dms/servicerequest, roles: [ROLE_ADMIN,ROLE_DMS_USER,ROLE_ACCOUNTING,ROLE_SALES,ROLE_PARTS_DMS,ROLE_SERVICE_DMS,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS] }
        - { path: ^/dms/supportform/new, roles: [ROLE_ADMIN,ROLE_DMS_USER,ROLE_REGULAR_ADMIN_DMS,ROLE_ACCOUNTING,ROLE_PARTS_DMS,ROLE_SERVICE_DMS,ROLE_FINANCE_DMS,ROLE_WHOLESALE_DMS,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS,ROLE_SALE4_DMS,ROLE_REGULAR_ADMIN_DMS] }
        - { path: ^/dms/supportform/create, roles: [ROLE_ADMIN,ROLE_DMS_USER,ROLE_REGULAR_ADMIN_DMS,ROLE_ACCOUNTING,ROLE_PARTS_DMS,ROLE_SERVICE_DMS,ROLE_FINANCE_DMS,ROLE_WHOLESALE_DMS,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS,ROLE_SALE4_DMS,ROLE_REGULAR_ADMIN_DMS] }
        - { path: ^/dms/supportform/, roles: [ROLE_ADMIN] }


        # inventory Images (listings,items)
        - { path: ^/dms/inventory/view, roles: [ROLE_WHOLESALE_DMS, ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS,ROLE_DEALER_PRINCIPAL, ROLE_SALE4_DMS] }
        - { path: ^/dms/inventory/sales, roles: [ROLE_ADMIN, ROLE_BUSINES, ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/inventory/archived, roles: [ROLE_ADMIN, ROLE_DMS_USER, ROLE_BUSINES,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/inventory/[0-9]+/edit, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/inventory/[0-9]+/new, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/inventory/[0-9]+/images, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/inventory/[0-9]+/imagesupload, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/inventory/[0-9]+/addvideo, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/inventory/activate, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/inventory/deactivate, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/admin/items/image_order, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN,ROLE_DMS_USER,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/admin/itemsfield/delete, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN,ROLE_DMS_USER,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/admin/imagecarousel/upload, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN,ROLE_DMS_USER,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/admin/items/[0-9]+/imagesupload, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN,ROLE_DMS_USER,ROLE_SALES,ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }

        - { path: ^/dms/inventory/additem, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES, ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/inventory/delete, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_DEALER_PRINCIPAL] }
        - { path: ^/dms/inventory, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES,ROLE_DEALER_PRINCIPAL, ROLE_SALE3_DMS, ROLE_SALE2_DEALER_GROUP_DMS] }

        - { path: ^/dms/, roles: [ROLE_ADMIN,ROLE_DMS_USER,ROLE_ACCOUNTING,ROLE_SALES,ROLE_PARTS_DMS,ROLE_SERVICE_DMS,ROLE_FINANCE_DMS,ROLE_WHOLESALE_DMS, ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS, ROLE_SALE4_DMS,ROLE_DEALER_PRINCIPAL] }
#        - { path: ^/dms, roles: [ROLE_ADMIN,ROLE_DMS_USER, ROLE_WHOLESALE_DMS, ROLE_SALE2_DMS,ROLE_SALE2_DEALER_GROUP_DMS, ROLE_SALE3_DMS] }
#        - { path: ^/dms/, roles: [ROLE_ADMIN,ROLE_DMS_USER,ROLE_ACCOUNTING,ROLE_SALES,ROLE_PARTS_DMS,ROLE_SERVICE_DMS] }
        - { path: ^/admin/featuredimport, roles: [ROLE_ADMIN] }
        - { path: ^/admin/items/additem/, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/items/additem, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/itemsfield/[0-9]+/delete, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/itemsfield/[0-9]+/delete/, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/items/[0-9]+, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/catalogs/[0-9]+/update/, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/catalogs/[0-9]+/update, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/catalogs/[0-9]+, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }




        - { path: ^/admin/items, roles: [ROLE_ADMIN,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/items/, roles: [ROLE_ADMIN,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/featuredimport, roles: [ROLE_ADMIN] }
        - { path: ^/admin/feed_api, roles: [ROLE_ADMIN] }
        - { path: ^/admin/categories, roles: [ROLE_ADMIN] }
        - { path: ^/admin/user_group, roles: [ROLE_ADMIN] }
        - { path: ^/admin/command_log, roles: [ROLE_ADMIN] }
        - { path: ^/admin/setting, roles: [ROLE_ADMIN] }
        - { path: ^/admin, roles: [ROLE_ADMIN,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/, roles: [ROLE_ADMIN,ROLE_DEALER_ADMIN] }


    providers:
        chain_provider:
            chain:
                providers: [main, busines,dealerGroup, dms ]
        dms:
            entity: { class: Numa\DOADMSBundle\Entity\DMSUser}
        dealerGroup:
            entity: { class: Numa\DOADMSBundle\Entity\DealerGroup}
        busines:
            entity: { class: Numa\DOAAdminBundle\Entity\Catalogrecords}
        main:
            entity: { class: Numa\DOAAdminBundle\Entity\User }

    encoders:
        Numa\DOADMSBundle\Entity\DMSUser: sha512
        Numa\DOAAdminBundle\Entity\Catalogrecords: sha512
        Numa\DOADMSBundle\Entity\DealerGroup: sha512
        Numa\DOAAdminBundle\Entity\User: sha512