security:
    access_denied_url: /error/403
    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_BUSINES:    ROLE_BUSINES
        ROLE_DEALER_ADMIN:    ROLE_DEALER_ADMIN
        ROLE_DMS_USER:      ROLE_DMS_USER
        ROLE_ADMIN:      ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH,ROLE_BUSINES,ROLE_DEALER_ADMIN,ROLE_DMS_USER]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /user/login
                check_path:  /login_check
                default_target_path: /dms
                success_handler: login_success_handler
            logout:
                path:   /logout
                target: /
 
    access_control:

        - { path: ^/admin/items/additem/, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/items/additem, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/itemsfield/[0-9]+/delete, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/itemsfield/[0-9]+/delete/, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/items/[0-9]+, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/catalogs/[0-9]+/update/, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/catalogs/[0-9]+/update, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/catalogs/[0-9]+, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/items/image_order, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/items/image_order, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/itemsfield/delete, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/imagecarousel/upload, roles: [ROLE_ADMIN, ROLE_BUSINES,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/items, roles: [ROLE_ADMIN,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/items/, roles: [ROLE_ADMIN,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/featuredimport, roles: [ROLE_ADMIN] }
        - { path: ^/admin/feed_api, roles: [ROLE_ADMIN] }
        - { path: ^/admin/categories, roles: [ROLE_ADMIN] }
        - { path: ^/admin/user_group, roles: [ROLE_ADMIN] }
        - { path: ^/admin/command_log, roles: [ROLE_ADMIN] }
        - { path: ^/admin/setting, roles: [ROLE_ADMIN] }
        - { path: ^/admin, roles: [ROLE_ADMIN,ROLE_DEALER_ADMIN] }
        - { path: ^/admin/, roles: [ROLE_ADMIN,ROLE_DEALER_ADMIN] }


        - { path: ^/dms/users_groups, roles: [ROLE_ADMIN] }
        - { path: ^/dms/userprofile, roles: [ROLE_ADMIN,ROLE_DMS_USER,ROLE_ACCOUNTING,ROLE_SALES,ROLE_PARTS_DMS,ROLE_SERVICE_DMS,ROLE_FINANCE_DMS,ROLE_WHOLESALE_DMS] }
        - { path: ^/dms/dmsuser, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_SALES] }
        - { path: ^/dms/user, roles: [ROLE_ADMIN,ROLE_BUSINES] }
        - { path: ^/dms/profile, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER] }
        - { path: ^/dms/finance, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_FINANCE_DMS] }
        - { path: ^/dms/customer, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER] }
        - { path: ^/dms/listing_form, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES] }
        - { path: ^/dms/themes, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER] }
        - { path: ^/dms/settings, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER] }
        - { path: ^/dms/image_carousel, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER] }
        - { path: ^/dms/command_log, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER] }
        - { path: ^/dms/reports, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER] }
        - { path: ^/dms/partrequest, roles: [ROLE_ADMIN,ROLE_DMS_USER,ROLE_ACCOUNTING,ROLE_SALES,ROLE_PARTS_DMS,ROLE_SERVICE_DMS] }
        - { path: ^/dms/servicerequest, roles: [ROLE_ADMIN,ROLE_DMS_USER,ROLE_ACCOUNTING,ROLE_SALES,ROLE_PARTS_DMS,ROLE_SERVICE_DMS] }
        - { path: ^/dms/inventory/view, roles: [ROLE_WHOLESALE_DMS] }
        - { path: ^/dms/inventory/cost, roles: [ROLE_WHOLESALE_DMS] }
        - { path: ^/dms/inventory/sales, roles: [ROLE_WHOLESALE_DMS] }
        - { path: ^/dms/inventory, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES] }
        - { path: ^/dms/inventory/delete, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES] }
        - { path: ^/dms/inventory/deactivate, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES] }
        - { path: ^/dms/inventory/activate, roles: [ROLE_ADMIN,ROLE_BUSINES,ROLE_DMS_USER,ROLE_SALES] }
        - { path: ^/dms/, roles: [ROLE_ADMIN,ROLE_DMS_USER,ROLE_ACCOUNTING,ROLE_SALES,ROLE_PARTS_DMS,ROLE_SERVICE_DMS,ROLE_FINANCE_DMS,ROLE_WHOLESALE_DMS] }
        - { path: ^/dms, roles: [ROLE_ADMIN,ROLE_DMS_USER,ROLE_WHOLESALE_DMS] }
#        - { path: ^/dms/, roles: [ROLE_ADMIN,ROLE_DMS_USER,ROLE_ACCOUNTING,ROLE_SALES,ROLE_PARTS_DMS,ROLE_SERVICE_DMS] }




    providers:
        chain_provider:
            chain:
                providers: [main, busines,dms]
        main:
            entity: { class: Numa\DOAAdminBundle\Entity\User }
        busines:
            entity: { class: Numa\DOAAdminBundle\Entity\Catalogrecords}
        dms:
            entity: { class: Numa\DOADMSBundle\Entity\DMSUser, property: username}
 
    encoders:
        Numa\DOAAdminBundle\Entity\User: sha512
        Numa\DOAAdminBundle\Entity\Catalogrecords: sha512
        Numa\DOADMSBundle\Entity\DMSUser: sha512