Numa\DOASettingsBundle\Entity\Setting:
    type: entity
    table: setting
    repositoryClass: Numa\DOASettingsBundle\Repository\SettingRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    indexes:
        name:
            columns: [ name ]
    fields:
        name:
            type: string
            length: 255
        value:
            type: string
            length: 255
            nullable: true
        value2:
            type: string
            length: 255
            nullable: true
        value3:
            type: string
            length: 255
            nullable: true
        value4:
            type: string
            length: 255
            nullable: true
        value5:
            type: string
            length: 255
            nullable: true
        value6:
            type: string
            length: 255
            nullable: true
        value7:
            type: string
            length: 255
            nullable: true
        value8:
            type: string
            length: 255
            nullable: true
        value9:
            type: string
            length: 255
            nullable: true
        value10:
            type: string
            length: 255
            nullable: true
        section:
            type: string
            length: 255
            nullable: true
        dealer_id:
            type: integer
            nullable: true
    manyToOne:
        Dealer:
            targetEntity: Numa\DOAAdminBundle\Entity\Catalogrecords
            inversedBy: Settings
            joinColumn:
                name: dealer_id
                referencedColumnName: id