Numa\DOASettingsBundle\Entity\Setting:
    type: entity
    table: setting
    repositoryClass: Numa\DOASettingsBundle\Repository\SettingRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    indexes:
        name:
            columns: [ name ]
    fields:
        name:
            type: string
            length: 255
        value:
            type: string
            length: 255
        section:
            type: string
            length: 255
        dealer_id:
            type: integer
            nullable: true
    manyToOne:
        Dealer:
            targetEntity: Numa\DOAAdminBundle\Entity\Catalogrecords
            inversedBy: Settings
            joinColumn:
                name: dealer_id
                referencedColumnName: id