Numa\DOASettingsBundle\Entity\Setting:
    type: entity
    table: setting
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    indexes:
        name:
            columns: [ name ]
    fields:
        name:
            type: string
            length: 255
        value:
            type: string
            length: 255
        section:
            type: string
            length: 255
