Numa\DOADMSBundle\Entity\Component:
    type: entity
    table: component

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        page_id:
            type: integer
            nullable: true
        name:
            type: string
            length: 255
            nullable: true
        type:
            type: string
            length: 255
            nullable: true
        value:
             type: text
             nullable: true
        settings:
             type: text
             nullable: true
        date_updated:
             type: datetime
             nullable: true
        date_created:
             type: datetime
             nullable: true
        status:
             type: string
             length: 255
             nullable: true
    manyToOne:
        Page:
            targetEntity: Numa\DOAModuleBundle\Entity\Page
            inversedBy: Component
            joinColumn:
                name: page_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]