Numa\DOADMSBundle\Entity\DealerGroup:
    type: entity
    table: dealer_group
#    repositoryClass: Numa\DOADMSBundle\Repository\DealerGroupRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            unique: true
        status:
            type: string
            length: 255
            nullable: true
        date_created:
            type: datetime
            nullable: true
        date_updated:
            type: datetime
            nullable: true
        dealer_id:
            type: integer
            nullable: true

    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
    oneToMany:
        Dealer:
            targetEntity: Numa\DOAAdminBundle\Entity\Catalogrecords
            mappedBy: DealerGroup
            cascade: [persist]
    manyToOne:
        DealerCreator:
            targetEntity: Numa\DOAAdminBundle\Entity\Catalogrecords
            inversedBy: DealerGroup
            joinColumn:
                name: dealer_id
                referencedColumnName: id