Numa\DOADMSBundle\Entity\FillablePdf:
    type: entity
    table: fillable_pdf
    repositoryClass: Numa\DOADMSBundle\Repository\FillablePdfRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            nullable: true
            length: 255
        state:
            type: string
            nullable: true
            length: 255
        media_id:
            type: integer
            nullable: true
    oneToOne:
        Media:
            targetEntity: Numa\DOADMSBundle\Entity\Media
            cascade: ["persist","remove"]
            #inversedBy: FillablePdf
            fetch: EAGER
            joinColumn:
                name: media_id
                referencedColumnName: id
    oneToMany:
        BillingDoc:
            targetEntity: Numa\DOADMSBundle\Entity\BillingDoc
            mappedBy: FillablePdf
            cascade: [persist,remove]
        FillablePdfField:
            targetEntity: Numa\DOADMSBundle\Entity\FillablePdfField
            mappedBy: FillablePdf
            cascade: [persist,remove]
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
