Numa\DOADMSBundle\Entity\Media:
    type: entity
    table: media
    indexes:
        fk_media_mediathek1_idx:
            columns:
                - mediathek_id
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        content:
            type: text
            nullable: false
            length: 16777215
            options:
                fixed: false
        mimetype:
            type: string
            nullable: false
            length: 255
        origin:
            type: string
            nullable: true
            length: 255
        date_created:
            type: datetime
            nullable: true

    manyToOne:
        mediathek:
            targetEntity: Mediathek
            cascade: 
                - all
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                mediathek_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
