Numa\DOADMSBundle\Entity\Note:
    type: entity
    table: note

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        customer_id:
            type: integer
            nullable: true
        subject:
            type: string
            length: 255
            nullable: true
        notes:
            type: string
            length: 255
            nullable: true
        date_remind:
             type: datetime
             nullable: true
        date_created:
             type: datetime
             nullable: true
        date_updated:
             type: datetime
             nullable: true
        status:
             type: string
             length: 255
             nullable: true
    manyToOne:
        Customer:
            targetEntity: Customer
            inversedBy: Note
            joinColumn:
                name: customer_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]