<?php

namespace Numa\CCCAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Numa\CCCAdminBundle\Entity\Settings;

/**
 * CommandLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends EntityRepository
{

    public function getValue($name){
        $qb = $this->getEntityManager()
            ->createQueryBuilder();
        $qb->select('s')->distinct()
            ->add('from', 'NumaCCCAdminBundle:Settings s');
        $qb->orWhere('s.name=:name');
        $qb->setParameter('name', $name);
        $qb->setMaxResults(1);
        $setting = $qb->getQuery()->getOneOrNullResult();
        if($setting instanceof Settings){
            return $setting->getValue();
        }
        return "";
    }

}
