#componentxxx:
#    path:     /
#    defaults: { _controller: "NumaDOAModuleBundle:Component:index" }
#
#component_show:
#    path:     /{id}/show
#    defaults: { _controller: "NumaDOAModuleBundle:Component:show" }
#
#componentxxx_new:
#    path:     /new
#    defaults: { _controller: "NumaDOAModuleBundle:Component:new" }
#
#componentxxx_create:
#    path:     /create
#    defaults: { _controller: "NumaDOAModuleBundle:Component:create" }
#    requirements: { method: post }
#
#component_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "NumaDOAModuleBundle:Component:edit" }
#
#component_update:
#    path:     /{id}/update
#    defaults: { _controller: "NumaDOAModuleBundle:Component:update" }
#    requirements: { method: post|put }
#
#component_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "NumaDOAModuleBundle:Component:delete" }
#    requirements: { method: post|delete }
