page:
    path:     /
    defaults: { _controller: "NumaDOAModuleBundle:Page:index" }

page_show:
    path:     /{id}/show
    defaults: { _controller: "NumaDOAModuleBundle:Page:show" }

page_new:
    path:     /new
    defaults: { _controller: "NumaDOAModuleBundle:Page:new" }

page_create:
    path:     /create
    defaults: { _controller: "NumaDOAModuleBundle:Page:create" }
    requirements: { method: post }

page_edit:
    path:     /{id}/edit
    defaults: { _controller: "NumaDOAModuleBundle:Page:edit" }

page_load_ads:
    path:     /{id}/load_ads
    defaults: { _controller: "NumaDOAModuleBundle:Page:loadAds" }


page_update:
    path:     /{id}/update
    defaults: { _controller: "NumaDOAModuleBundle:Page:update" }
    requirements: { method: post|put }

page_delete:
    path:     /{id}/delete
    defaults: { _controller: "NumaDOAModuleBundle:Page:delete" }
    requirements: { method: post|delete }
