parameters:
#    numa_doa_api.example.class: Numa\DOAApiBundle\Example

services:
#    numa_doa_api.example:
#        class: %numa_doa_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
