dms_ad_index:
    path:     /
    defaults: { _controller: "NumaDOAModuleBundle:Ad:index",_dashboard:"DMS" }

ad_show:
    path:     /{id}/show
    defaults: { _controller: "NumaDOAModuleBundle:Ad:show" }

dms_ad_new:
    path:     /new
    defaults: { _controller: "NumaDOAModuleBundle:Ad:new",_dashboard:"DMS" }

ad_newAjax:
    path:     /newAjax/{pageid}
    defaults: { _controller: "NumaDOAModuleBundle:Ad:newAjax" }

dms_ad_create:
    path:     /create
    defaults: { _controller: "NumaDOAModuleBundle:Ad:create",_dashboard:"DMS" }
    requirements: { _method: post }

dms_ad_edit:
    path:     /{id}/edit
    defaults: { _controller: "NumaDOAModuleBundle:Ad:edit",_dashboard:"DMS" }

ad_editAjax:
    path:     /{id}/editAjax
    defaults: { _controller: "NumaDOAModuleBundle:Ad:editAjax" }

dms_ad_update:
    path:     /{id}/update
    defaults: { _controller: "NumaDOAModuleBundle:Ad:update",_dashboard:"DMS" }
    requirements: { _method: post|put }

dms_ad_delete:
    path:     /{id}/delete
    defaults: { _controller: "NumaDOAModuleBundle:Ad:delete",_dashboard:"DMS" }

