billing:
    path:     /
    defaults: { _controller: "NumaDOADMSBundle:Billing:index" }
billing2:
    path:     /2
    defaults: { _controller: "NumaDOADMSBundle:Billing:index2" }
billing_show:
    path:     /{id}/show
    defaults: { _controller: "NumaDOADMSBundle:Billing:show" }

billing_new:
    path:     /new/{id}
    defaults: { _controller: "NumaDOADMSBundle:Billing:new" }
billing_new_no_customer:
    path:     /newnc
    defaults: { _controller: "NumaDOADMSBundle:Billing:newnc" }

billing_create:
    path:     /create
    defaults: { _controller: "NumaDOADMSBundle:Billing:create" }
    requirements: { method: post }

billing_edit:
    path:     /{id}/edit
    defaults: { _controller: "NumaDOADMSBundle:Billing:edit" }

billing_update:
    path:     /{id}/update
    defaults: { _controller: "NumaDOADMSBundle:Billing:update" }
    requirements: { method: post|put }

billing_delete:
    path:     /{id}/delete
    defaults: { _controller: "NumaDOADMSBundle:Billing:delete" }
#    requirements: { method: post|delete }
billing_print:
    path:     /{id}/print
    defaults: { _controller: "NumaDOADMSBundle:Billing:print" }

billing_print_blank:
    path:     /printblank
    defaults: { _controller: "NumaDOADMSBundle:Billing:printBlank" }

billing_print_inside:
    path:     /{id}/print_inside
    defaults: { _controller: "NumaDOADMSBundle:Billing:printInside" }
billing_mass_delete:
    path:     /deletex
    defaults: { _controller: "NumaDOADMSBundle:Billing:massDelete" }
