dms_catalogs:
    pattern:  /
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:index",_dashboard:"DMS" }
dms_catalogs_show:
    pattern:  /{id}/show
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:show",_dashboard:"DMS" }
dms_catalogs_new:
    pattern:  /new
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:new",_dashboard:"DMS" }
dms_catalogs_create:
    pattern:  /create
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:create",_dashboard:"DMS" }
    requirements: { _method: post }
dms_catalogs_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:edit",_dashboard:"DMS" }
dms_catalogs_update:
    pattern:  /{id}/update
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:update",_dashboard:"DMS" }
    requirements: { _method: post|put }
dms_catalogs_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:delete",_dashboard:"DMS" }
#    requirements: { _method: post|delete }
dms_catalog_import_csv:
    pattern:  /proccessCSV
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:proccessImportCSV",_dashboard:"DMS" }
    requirements: { _method: post }
dms_coupons_update:
    path:     /{id}/update_coupons
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:updateCoupons",_dashboard:"DMS" }
    requirements: { _method: post|put }
dms_catalogs_site_update:
    path:     /{id}/update_site
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:updateSite",_dashboard:"DMS" }
    requirements: { _method: post|put }

