dms_catalogs:
    path:  /
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:index",_dashboard:"DMS" }
dms_catalogs_show:
    path:  /{id}/show
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:show",_dashboard:"DMS" }
dms_catalogs_new:
    path:  /new
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:new",_dashboard:"DMS" }
dms_catalogs_create:
    path:  /create
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:create",_dashboard:"DMS" }
    requirements: { _method: post }
dms_catalogs_edit:
    path:  /{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:edit",_dashboard:"DMS" }
dms_catalogs_update:
    path:  /{id}/update
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:update",_dashboard:"DMS" }
    requirements: { _method: post|put }
dms_catalogs_activate:
    path:  /{id}/activate
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:activateDealer",_dashboard:"DMS" }
dms_catalogs_delete:
    path:  /{id}/delete
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:delete",_dashboard:"DMS" }
#    requirements: { _method: post|delete }
dms_catalog_import_csv:
    path:  /proccessCSV
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:proccessImportCSV",_dashboard:"DMS" }
    requirements: { _method: post }
dms_coupons_update:
    path:     /{id}/update_coupons
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:updateCoupons",_dashboard:"DMS" }
    requirements: { _method: post|put }
dms_catalogs_site_update:
    path:     /{id}/update_site
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:updateSite",_dashboard:"DMS" }
    requirements: { _method: post|put }
dms_catalogs_item_default_update:
    path:     /{id}/update_item_default
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:updateItemDefault",_dashboard:"DMS" }
    requirements: { _method: post|put }
dms_catalogs_feeds_update:
    path:     /{id}/update_feeds
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:updateFeeds",_dashboard:"DMS" }
    requirements: { _method: post|put }
dms_catalogs_billing_update:
    path:     /{id}/update_billing
    defaults: { _controller: "NumaDOAAdminBundle:Catalogrecords:updateBilling",_dashboard:"DMS" }