dms_command_log_home:
    path:  /
    defaults: { _controller: "NumaDOAAdminBundle:CommandLog:index",_dashboard:"DMS" }
dms_command_log_detail:
    path:  /details/{id}
    defaults: { _controller: "NumaDOAAdminBundle:CommandLog:details",_dashboard:"DMS" }
dms_command_log_start:
    path:  /start
    defaults: { _controller: "NumaDOAAdminBundle:CommandLog:start",_dashboard:"DMS" }