#component:
#    path:     /
#    defaults: { _controller: "NumaDOAModuleBundle:Component:index" }
#
#component_show:
#    path:     /{id}/show
#    defaults: { _controller: "NumaDOAModuleBundle:Component:show" }
#
#component_new:
#    path:     /new
#    defaults: { _controller: "NumaDOAModuleBundle:Component:new" }

#component_create:
#    path:     /create
#    defaults: { _controller: "NumaDOAModuleBundle:Component:create" }
#    requirements: { _method: post }
#
component_edit:
    path:     /{id}/edit
    defaults: { _controller: "NumaDOAModuleBundle:Component:edit",_dashboard:"DMS" }

component_update:
    path:     /{id}/update
    defaults: { _controller: "NumaDOAModuleBundle:Component:update",_dashboard:"DMS" }
    requirements: { _method: post|put }

component_delete:
    path:     /{id}/delete
    defaults: { _controller: "NumaDOAModuleBundle:Component:delete",_dashboard:"DMS" }
    requirements: { _method: post|delete }
