customer:
    path:     /
    defaults: { _controller: "NumaDOADMSBundle:Customer:index" }

customer_show:
    path:     /{id}/show
    defaults: { _controller: "NumaDOADMSBundle:Customer:show" }

customer_new:
    path:     /new
    defaults: { _controller: "NumaDOADMSBundle:Customer:new" }

customer_create:
    path:     /create
    defaults: { _controller: "NumaDOADMSBundle:Customer:create" }
    requirements: { method: post }
customer_create_ajax:
    path:     /createAjax
    defaults: { _controller: "NumaDOADMSBundle:Customer:createAjax" }
    requirements: { method: post }

customer_edit:
    path:     /{id}/edit
    defaults: { _controller: "NumaDOADMSBundle:Customer:edit" }

customer_update:
    path:     /{id}/update
    defaults: { _controller: "NumaDOADMSBundle:Customer:update" }
    requirements: { method: post|put }

customer_delete:
    path:     /{id}/delete
    defaults: { _controller: "NumaDOADMSBundle:Customer:delete" }
    requirements: { method: post|delete }

customer_addnote:
    path:     /{id}/addnote
    defaults: { _controller: "NumaDOADMSBundle:Note:new" }

customer_shownote:
    path:     /{id}/shownote
    defaults: { _controller: "NumaDOADMSBundle:Note:index" }

customer_notes:
    path:     /notes.html
    defaults: { _controller: "NumaDOADMSBundle:Note:notes" }

customer_addbilling:
    path:     /{id}/addbilling
    defaults: { _controller: "NumaDOADMSBundle:Billing:new" }

customer_addreminder:
    path:     /{id}/addreminder
    defaults: { _controller: "NumaDOADMSBundle:Reminder:new" }

billing_report_xls:
    path:     /{id}/report_xls
    defaults: { _controller: "NumaDOADMSBundle:Customer:reportXls" }

customer_export_csv:
    path:     /export_csv
    defaults: { _controller: "NumaDOADMSBundle:Customer:exportCsv" }
dms_customer_delete:
    path:     /delete
    defaults: { _controller: "NumaDOAAdminBundle:Customer:massDelete2" }