dms_home:
    path:  /
    defaults: { _controller: "NumaDOADMSBundle:Default:index" }
dms_customer:
        resource: "@NumaDOADMSBundle/Resources/config/routing/customer.yml"
        prefix:   /customers
#dms_customer:
#    defaults: { _controller: "NumaDOADMSBundle:Dms:customers" }
#    path:   /customers
#dms_activate:
#    path:  /dms_activate
#    defaults: { _controller: "NumaDOADMSBundle:Dms:activate" }
#dms_activate_success:
#    path:  /dms_activate_success
#    defaults: { _controller: "NumaDOADMSBundle:Dms:activateSuccess" }
dms_user:
    path:  /users
    defaults: { _controller: "NumaDOADMSBundle:Dms:users" }

NumaDOADMSBundle_client:
    resource: "@NumaDOADMSBundle/Resources/config/routing/client.yml"
    prefix:   /client
