dms_home:
    path:  /
    defaults: { _controller: "NumaDOADMSBundle:Default:index" }
dms_customer:
        resource: "@NumaDOADMSBundle/Resources/config/routing/customer.yml"
        prefix:   /customers
#dms_customer:
#    defaults: { _controller: "NumaDOADMSBundle:Dms:customers" }
#    path:   /customers
dms_activate:
    path:  /activate
    defaults: { _controller: "NumaDOADMSBundle:Dms:activate" }
dms_user:
    path:  /users
    defaults: { _controller: "NumaDOADMSBundle:Dms:users" }