dms_importfeed:
    path:  /feed
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:index",_dashboard:"DMS" }
dms_mapping:
    path:  /mapping
    defaults: { _controller: "NumaDOAAdminBundle:Mapping:index",_dashboard:"DMS" }
dms_mapping_feed:
    path:  /mapping/{id}
    defaults: { _controller: "NumaDOAAdminBundle:Mapping:mapping",_dashboard:"DMS" }

dms_importfeed_show:
    path:  /{id}/show
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:show",_dashboard:"DMS" }

dms_importfeed_new:
    path:  /new
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:new",_dashboard:"DMS" }

dms_importfeed_create:
    path:  /create
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:create",_dashboard:"DMS" }
    requirements: { method: post }

dms_importfeed_edit:
    path:  /{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:edit",_dashboard:"DMS" }

dms_importfeed_update:
    path:  /{id}/update
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:update",_dashboard:"DMS" }
    requirements: { method: post|put }

dms_importfeed_delete:
    path:  /{id}/delete
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:delete",_dashboard:"DMS" }
    requirements: { method: post|delete }
dms_importfeed_items_delete:
    path:  /{id}/delete_items
    defaults: { _controller: "NumaDOAAdminBundle:Importfeed:deleteItems",_dashboard:"DMS" }
