inventory:
    path:     /
    defaults: { _controller: "NumaDOADMSBundle:Inventory:index",_dashboard: "DMS" }
inventory_view:
    path:     /view
    defaults: { _controller: "NumaDOADMSBundle:Inventory:view",_dashboard: "DMS" }
inventory_cost:
    path:     /cost
    defaults: { _controller: "NumaDOADMSBundle:Inventory:cost",_dashboard: "DMS" }
inventory_sales:
    path:     /sales
    defaults: { _controller: "NumaDOADMSBundle:Inventory:sales",_dashboard: "DMS" }
inventory_kijiji:
    path:     /kijiji
    defaults: { _controller: "NumaDOADMSBundle:Inventory:kijiji",_dashboard: "DMS" }
inventory_autotrader:
    path:     /autotrader
    defaults: { _controller: "NumaDOADMSBundle:Inventory:autotrader",_dashboard: "DMS" }
inventory_archived:
    path:     /archived
    defaults: { _controller: "NumaDOADMSBundle:Inventory:archived",_dashboard: "DMS" }
dms_additem:
    path:  /additem
    defaults: { _controller: "NumaDOAAdminBundle:Item:additem",_dashboard: "DMS" }
dms_items_new:
    path:  /{cat_id}/new
    defaults: { _controller: "NumaDOAAdminBundle:Item:new",_dashboard: "DMS" }
dms_items_edit:
    path:  /{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:Item:edit",_dashboard: "DMS" }
dms_item_activate:
    path:     /activate
    defaults: { _controller: "NumaDOAAdminBundle:Item:massActivate2" }
dms_item_deactivate:
    path:     /deactivate
    defaults: { _controller: "NumaDOAAdminBundle:Item:massDeactivate2" }
dms_item_featured:
    path:     /featured
    defaults: { _controller: "NumaDOAAdminBundle:Item:massMakeFeatured2" }
dms_item_kijiji:
    path:     /kijiji
    defaults: { _controller: "NumaDOAAdminBundle:Item:massMakeKijiji" }
dms_item_feed_kijiji_add:
    path:     /kijiji_add
    defaults: { _controller: "NumaDOAAdminBundle:Item:kijijiAdd" }
dms_item_feed_kijiji_remove:
    path:     /kijiji_remove
    defaults: { _controller: "NumaDOAAdminBundle:Item:kijijiRemove" }
dms_item_feed_autotrader_add:
    path:     /autotrader_add
    defaults: { _controller: "NumaDOAAdminBundle:Item:autotraderAdd" }
dms_item_feed_autotrader_remove:
    path:     /autotrader_remove
    defaults: { _controller: "NumaDOAAdminBundle:Item:autotraderRemove" }
dms_item_QB:
    path:     /addtoqb
    defaults: { _controller: "NumaDOAAdminBundle:Item:massAddToQB" }
dms_item_QBPO:
    path:     /addtoqbpo
    defaults: { _controller: "NumaDOAAdminBundle:Item:massAddToQBPO" }
dms_item_delete:
    path:     /delete
    defaults: { _controller: "NumaDOAAdminBundle:Item:massDelete2" }
dms_item_category_change:
    path:  /{id}/category
    defaults: { _controller: "NumaDOAAdminBundle:Item:changeCategory",_dashboard: "DMS" }
    requirements: { method: post|put }
dms_item_images:
    path: /{id}/images
    defaults: { _controller: "NumaDOAAdminBundle:Image:show",_dashboard: "DMS" }
dms_item_print:
    path: /{id}/print
    defaults: { _controller: "NumaDOADMSBundle:Inventory:print",_dashboard: "DMS" }
dms_item_images_upload:
    path: /{id}/imagesupload
    defaults: { _controller: "NumaDOAAdminBundle:Image:upload",_dashboard: "DMS" }
    requirements: { id: \d+ }
dms_item_image_setorder:
    path: /image_order
    defaults: { _controller: "NumaDOAAdminBundle:Image:setImageOrder",_dashboard: "DMS" }
    condition: "request.isXmlHttpRequest()"
dms_item_images_add_video:
    path: /{id}/addvideo
    defaults: { _controller: "NumaDOAAdminBundle:Image:addVideo",_dashboard: "DMS" }
    requirements: { id: \d+ }
dms_item_recover:
    path:     /recover
    defaults: { _controller: "NumaDOAAdminBundle:Item:massRecover" }
#inventory_new:
#    path:     /new
#    defaults: { _controller: "NumaDOADMSBundle:Inventory:new" }
#
#customer_create:
#    path:     /create
#    defaults: { _controller: "NumaDOADMSBundle:Customer:create" }
#    requirements: { method: post }
#
#customer_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "NumaDOADMSBundle:Customer:edit" }
#
#customer_update:
#    path:     /{id}/update
#    defaults: { _controller: "NumaDOADMSBundle:Customer:update" }
#    requirements: { method: post|put }
#
#customer_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "NumaDOADMSBundle:Customer:delete" }
#    requirements: { method: post|delete }
#
#customer_addnote:
#    path:     /{id}/addnote
#    defaults: { _controller: "NumaDOADMSBundle:Note:new" }
#
#customer_addbilling:
#    path:     /{id}/addbilling
#    defaults: { _controller: "NumaDOADMSBundle:Billing:new" }
#
#customer_shownote:
#    path:     /{id}/shownote
#    defaults: { _controller: "NumaDOADMSBundle:Note:index" }
#
#customer_notes:
#    path:     /notes.html
#    defaults: { _controller: "NumaDOADMSBundle:Note:notes" }
#
#customer_addbilling:
#    path:     /{id}/addbilling
#    defaults: { _controller: "NumaDOADMSBundle:Billing:new" }
