#dms_media_index:
#    path:     /
#    defaults: { _controller: "NumaDOADMSBundle:Media:printBuyerGuide" }
dms_media_buyersguide:
    path:     /buyersguide/{item}
    defaults: { _controller: "NumaDOADMSBundle:Media:printBuyerGuide"}
dms_media_show:
    path:     /{media}/show
    defaults: { _controller: "NumaDOADMSBundle:Media:show" }


