dms_quickbooks_index:
    path:     /
    defaults: { _controller: "NumaDOADMSBundle:Quickbooks:index" }
dms_quickbooks_launch:
    path:     /launch
    defaults: { _controller: "NumaDOADMSBundle:Quickbooks:launch" }
dms_quickbooks_disconect:
    path:     /disconect
    defaults: { _controller: "NumaDOADMSBundle:Quickbooks:disconect" }
dms_quickbooks_oauth_redirect:
    path:     /oauth
    defaults: { _controller: "NumaDOADMSBundle:Quickbooks:oauth" }

dms_quickbooks_test:
    path:     /test
    defaults: { _controller: "NumaDOADMSBundle:Quickbooks:landing" }

dms_quickbooks_custmers:
    path:     /customers
    defaults: { _controller: "NumaDOADMSBundle:Quickbooks:customers" }

dms_quickbooks_fetch_custmer:
    path:     /fetch_customer/{id}
    defaults: { _controller: "NumaDOADMSBundle:Quickbooks:fetchCustomerFromQB" }