sale:
    path:     /
    defaults: { _controller: "NumaDOADMSBundle:Sale:index" }

sale_show:
    path:     /{id}/show
    defaults: { _controller: "NumaDOADMSBundle:Sale:show" }

sale_new:
    path:     /new
    defaults: { _controller: "NumaDOADMSBundle:Sale:new" }

sale_create:
    path:     /create
    defaults: { _controller: "NumaDOADMSBundle:Sale:create" }
    requirements: { _method: post }

sale_edit:
    path:     /{id}/edit
    defaults: { _controller: "NumaDOADMSBundle:Sale:edit" }

sale_update:
    path:     /{id}/update
    defaults: { _controller: "NumaDOADMSBundle:Sale:update" }
    requirements: { _method: post|put }

sale_delete:
    path:     /{id}/delete
    defaults: { _controller: "NumaDOADMSBundle:Sale:delete" }
    requirements: { _method: post|delete }

sale_print_inside:
    path:     /{id}/print_inside
    defaults: { _controller: "NumaDOADMSBundle:Sale:printInside" }

sale_upload_related_docs:
    path:     /{id}/upload_docs
    defaults: { _controller: "NumaDOADMSBundle:Sale:uploadRelatedDocs" }
sale_refresh_related_docs:
    path:     /{id}/refresh_docs
    defaults: { _controller: "NumaDOADMSBundle:Sale:refreshRelatedDocs" }
sale_delete_related_docs:
    path:     /{id}/delete_docs
    defaults: { _controller: "NumaDOADMSBundle:Sale:deleteRelatedDocs" }