dms_setting:
    path:     /
    defaults: { _controller: "NumaDOASettingsBundle:Setting:index",_dashboard:"DMS" }
#
#setting_show:
#    path:     /{id}/show
#    defaults: { _controller: "NumaDOAAdminBundle:Setting:show" }

dms_setting_new:
    path:     /new
    defaults: { _controller: "NumaDOASettingsBundle:Setting:new",_dashboard:"DMS" }

dms_setting_create:
    path:     /create
    defaults: { _controller: "NumaDOASettingsBundle:Setting:create",_dashboard:"DMS" }
    requirements: { _method: post }
#
dms_setting_edit:
    path:     /{id}/edit
    defaults: { _controller: "NumaDOASettingsBundle:Setting:edit",_dashboard:"DMS" }
#
dms_setting_update:
    path:     /{id}/update
    defaults: { _controller: "NumaDOASettingsBundle:Setting:update",_dashboard:"DMS" }
    requirements: { _method: post|put }
#
#setting_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "NumaDOAAdminBundle:Setting:delete" }
#    requirements: { _method: post|delete }
