dms_user_groups:
    path:     /
    defaults: { _controller: "NumaDOAAdminBundle:UserGroup:index",_dashboard: "DMS" }

dms_user_group_new:
    path:  /new
    defaults: { _controller: "NumaDOAAdminBundle:UserGroup:new",_dashboard: "DMS"  }

dms_user_group_edit:
    path:  /{id}/edit
    defaults: { _controller: "NumaDOAAdminBundle:UserGroup:edit",_dashboard: "DMS"  }