<?php

namespace Numa\CCCSiteBundle\Repository;

/**
 * Ltd_formRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ltd_formRepository extends \Doctrine\ORM\EntityRepository
{
}
