services:
    Numa.Twig.numa_extension:
        class: Numa\Twig\NumaExtension
        tags:
           - { name: twig.extension } 
        arguments:  [@service_container]
    Numa.Twig.Settings:
        class: Numa\DOASettingsBundle\Twig\SettingsExtension
        tags:
           - { name: twig.extension }
        arguments:  [@Numa.Settings]
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
           - { name: twig.extension }
    Numa.Controller.Search:
        class: Numa\DOASiteBundle\Controller\SearchController
    Numa.Controller.Item:
        class: Numa\DOASiteBundle\Controller\ItemController
    Numa.Emailer:
        class: Numa\Lib\Emailer
        arguments: ["@service_container"]
    Numa.Dashboard.Stats:
        class: Numa\Lib\Stats
        arguments: ["@service_container"]
    Numa.Settings:
        class: Numa\DOASettingsBundle\Util\SettingsLib
        arguments: ["@doctrine.orm.entity_manager","@service_container"]
    numa.dynamicRouter.listener:
        class: Numa\DOASiteBundle\Services\ExtraLoader
        tags:
            - { name: routing.loader, priority: 33 }
    listener.requestresponse:
        class: Numa\DOASiteBundle\Services\ExtraListener
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }