services:
    Numa.Twig.numa_extension:
        class: Numa\Twig\NumaExtension
        tags:
           - { name: twig.extension } 
        arguments:  [@service_container]
    Numa.Controller.Search:
        class: Numa\DOASiteBundle\Controller\SearchController
    Numa.Controller.Item:
        class: Numa\DOASiteBundle\Controller\ItemController
    Numa.Emailer:
        class: Numa\Lib\Emailer
        arguments: ["@service_container"]