services:
    Numa.Twig.numa_extension:
        class: Numa\Twig\NumaExtension
        tags:
           - { name: twig.extension } 
        arguments:  ["@service_container","@listener.requestresponse"]
    Numa.Twig.Settings:
        class: Numa\DOASettingsBundle\Twig\SettingsExtension
        tags:
           - { name: twig.extension }
        arguments:  ["@Numa.Settings"]
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
           - { name: twig.extension }
    twig.extension.stringloader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: twig.extension }
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    Numa.Controller.Search:
        class: Numa\DOASiteBundle\Controller\SearchController
    Numa.Controller.Item:
        class: Numa\DOASiteBundle\Controller\ItemController
    Numa.Emailer:
        class: Numa\Lib\Emailer
        arguments: ["@service_container"]
    Numa.Dashboard.Stats:
        class: Numa\Lib\Stats
        arguments: ["@service_container"]
    Numa.Settings:
        class: Numa\DOASettingsBundle\Util\SettingsLib
        arguments: ["@doctrine.orm.entity_manager","@service_container"]
    numa.component.text:
        class: Numa\Util\Component\TextComponent
        arguments: ["@service_container"]
    numa.component.carousel:
        class: Numa\Util\Component\CarouselComponent
        arguments: ["@service_container"]
    numa.component:
        class: Numa\Util\Component\ComponentDispatch
        arguments: ["@service_container"]
    numa.dynamicRouter.listener:
        class: Numa\DOASiteBundle\Services\ExtraLoader
        arguments: ["@service_container" , "@security.token_storage"]
        tags:
            - { name: routing.loader, priority: 33 }
    listener.requestresponse:
        class: Numa\DOASiteBundle\Services\ExtraListener
        tags:
           #- { name: kernel.event_listener, event: kernel.view, method: onKernelView }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -10 }
           #- { name: kernel.event_listener, event: kernel.view, method: preExecute }

        arguments: [ "@service_container","@controller_resolver", "@request_stack", "@http_kernel" ]
    Numa.ListingForms:
        class: Numa\DOASiteBundle\Services\ListingFormHandler
        arguments: ["@service_container" ]
