parameters:
#    numa_doa_site.example.class: Numa\DOASiteBundle\Example

services:
#    numa_doa_site.example:
#        class: %numa_doa_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
