services:
    Numa.Twig.numa_extension:
        class: Numa\Twig\NumaExtension
        tags:
           - { name: twig.extension } 
    Numa.Controller.Search:
        class: Numa\DOASiteBundle\Controller\SearchController
    Numa.Controller.Item:
        class: Numa\DOASiteBundle\Controller\ItemController