Numa\DOAAdminBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
    properties:
        password:
            - NotBlank: ~
            - Length:
                min: 3
        email:
            - Email: ~
        username: